// `re-shell ui generate --prompt "..."`: AI-assisted component generation with a
// deterministic offline fallback. See utils/ui-generate.ts for the pipeline.

import chalk from 'chalk';
import { fail, ok } from '../utils/json-output';
import { createSpinner } from '../utils/spinner';
import { generateComponent, type GenerateDeps, type GenerateResult } from '../utils/ui-generate';
import { UiScaffoldError } from '../utils/ui-package';
import type { ComponentGroup } from '../utils/ui-component-templates';

/** Options of `ui generate`. */
export interface UiGenerateOptions {
  prompt?: string;
  name?: string;
  group?: string;
  workspace?: string;
  ui?: string;
  dryRun?: boolean;
  force?: boolean;
  /** Skip the AI provider even when one is configured. */
  offline?: boolean;
  json?: boolean;
}

/** `ui generate --json` payload: the result, without the source text unless this was a dry run. */
export type UiGenerateResponse = Omit<GenerateResult, 'sources'> & { sources?: GenerateResult['sources'] };

/** Run the command. `deps` is the test seam (mocked provider, fake typecheck). */
export async function runUiGenerate(options: UiGenerateOptions, deps: GenerateDeps = {}): Promise<void> {
  const json = Boolean(options.json);
  const spinner = json ? null : createSpinner('Generating component…', undefined, { json });
  spinner?.start();
  try {
    if (options.prompt === undefined || options.prompt.trim() === '') {
      throw new UiScaffoldError('--prompt "<description>" is required');
    }
    const result = await generateComponent(
      {
        prompt: options.prompt,
        name: options.name,
        group: options.group as ComponentGroup | undefined,
        workspace: options.workspace ?? process.cwd(),
        ui: options.ui,
        dryRun: options.dryRun,
        force: options.force,
        offline: options.offline,
      },
      deps
    );
    spinner?.stop();

    if (json) {
      const { sources, ...rest } = result;
      const payload: UiGenerateResponse = result.dryRun ? { ...rest, sources } : rest;
      ok(payload, result.warnings);
      return;
    }
    render(result);
  } catch (error) {
    spinner?.stop();
    if (error instanceof UiScaffoldError) {
      if (json) {
        fail('UI_GENERATE_ERROR', error.message, error.details);
      } else {
        process.stderr.write(chalk.red(`\n✗ ${error.message}\n`));
        process.exitCode = 1;
      }
      return;
    }
    throw error;
  } finally {
    spinner?.stop();
  }
}

function render(result: GenerateResult): void {
  const verb = result.dryRun ? 'Would create' : 'Created';
  process.stdout.write(chalk.cyan.bold(`\n▶ ui generate  ${result.name}\n\n`));
  if (result.offline) {
    process.stdout.write(chalk.yellow.bold('  OFFLINE') + chalk.yellow(' - no AI model was used; this is a deterministic template filled from your prompt.\n'));
    if (result.intent) {
      process.stdout.write(chalk.gray(`  kind: ${result.intent.kind}  fields: ${result.intent.fields.map((f) => `${f.key}:${f.type}`).join(', ')}\n`));
    }
  } else {
    process.stdout.write(chalk.gray(`  generated by ${result.provider}${result.model ? ` (${result.model})` : ''}\n`));
  }
  process.stdout.write(chalk.green(`  typecheck passed (tsc, ${result.typecheck.durationMs} ms, ${result.typecheck.attempts} attempt${result.typecheck.attempts === 1 ? '' : 's'})\n\n`));
  for (const file of result.files) process.stdout.write(`  ${chalk.green(verb)}  ${file}\n`);
  process.stdout.write(`  ${chalk.green(result.dryRun ? 'Would update' : 'Updated')}  ${result.barrel}\n`);
  for (const warning of result.warnings.slice(result.offline ? 1 : 0)) process.stdout.write(chalk.yellow(`  ! ${warning}\n`));
  if (result.dryRun) {
    process.stdout.write(chalk.gray('\n  Dry run: nothing was written. Re-run without --dry-run to write the files.\n'));
    process.stdout.write(`\n${chalk.bold(result.files[0])}\n${result.sources.component}\n`);
  }
  process.stdout.write('\n');
}
