// `re-shell cloud iac generate`: workspace v2 -> Terraform for AWS / Azure / GCP.

import * as fs from 'fs';
import * as path from 'path';

import { loadWorkspace, WorkspaceLoadError } from '../platform/workspace';
import { generateAws, type IacFile } from './aws';
import { generateAzure } from './azure';
import { generateGcp } from './gcp';
import { buildIacModel, resolveEnvRefs, IAC_PROVIDERS, type IacModel, type IacProvider } from './model';

export type IacErrorCode = 'WORKSPACE_NOT_FOUND' | 'SCHEMA_VALIDATION_ERROR' | 'IAC_ERROR';

export class IacError extends Error {
  constructor(
    public readonly code: IacErrorCode | 'IAC_VALIDATE_ERROR' | 'IAC_TERRAFORM_MISSING' | 'CLOUD_CREDENTIALS_MISSING' | 'CLOUD_DEPLOY_CONFIRMATION_REQUIRED' | 'CLOUD_DEPLOY_ERROR',
    message: string,
    public readonly details?: Record<string, unknown>
  ) {
    super(message);
    this.name = 'IacError';
  }
}

export interface GenerateIacOptions {
  cwd?: string;
  configPath?: string;
  provider: string;
  services?: string[];
  /** Output directory (required unless dryRun). */
  out?: string;
  dryRun?: boolean;
}

export interface GeneratedFile {
  path: string;
  bytes: number;
  content: string;
}

export interface IacVariable {
  name: string;
  type: string;
  description: string;
}

export interface GenerateIacResult {
  provider: IacProvider;
  target: string;
  outDir: string | null;
  dryRun: boolean;
  written: boolean;
  services: Array<{ name: string; port: number; exposed: boolean }>;
  files: GeneratedFile[];
  /** Variables the generated configuration accepts for image tags and regions. */
  variables: IacVariable[];
  warnings: string[];
}

const TARGETS: Record<IacProvider, string> = {
  aws: 'ECS Fargate',
  azure: 'Container Apps',
  gcp: 'Cloud Run',
};

function readme(provider: IacProvider, model: IacModel): string {
  const common = [
    `# ${model.project}: ${TARGETS[provider]} (Terraform)`,
    '',
    'Generated by `re-shell cloud iac generate`. Re-run the command to regenerate; edits to these files are overwritten.',
    '',
    '## Variables',
    '',
    '- `image_tags`: map of service name to image tag (`-var=\'image_tags={"api":"1.2.3"}\'`)',
    '- `default_image_tag`: tag used for services missing from `image_tags` (default `latest`)',
  ];
  const regionVar = provider === 'azure' ? '`location`' : '`region`';
  common.push(`- ${regionVar}: deployment ${provider === 'azure' ? 'location' : 'region'}`);
  const steps: Record<IacProvider, string[]> = {
    aws: [
      '1. `terraform init && terraform apply` creates the cluster, load balancer and ECR repositories.',
      '2. Push each service image to the URL in the `ecr_repository_urls` output, tagged as set in `image_tags`.',
      '3. Services reach each other by name through ECS Service Connect (for example `http://billing:8081`).',
    ],
    azure: [
      '1. `terraform init && terraform apply` creates the environment and container registry (placeholder image).',
      '2. Push each service image to `acr_login_server`, then re-apply with `-var use_placeholder_image=false`.',
      '3. Apps are reachable inside the environment; exposed services get a public HTTPS FQDN (`app_urls` output).',
    ],
    gcp: [
      '1. `terraform init && terraform apply -var project_id=<id>` creates the registry and services (placeholder image).',
      '2. Push each service image to the `artifact_registry` path, then re-apply with `-var use_placeholder_image=false`.',
      '3. Service-to-service URLs in env values are wired to the Cloud Run URIs and the caller is granted `roles/run.invoker`.',
    ],
  };
  return [...common, '', '## Deploy', '', ...steps[provider], '', 'Deploy with credentials via `re-shell cloud deploy --provider ' + provider + ' --dir <this directory> --yes`.', ''].join('\n');
}

function tfvarsExample(provider: IacProvider, model: IacModel): string {
  const tags = model.services.map(s => `  ${JSON.stringify(s.name)} = "latest"`).join('\n');
  const region = provider === 'azure' ? 'location = "westeurope"' : provider === 'gcp' ? 'project_id = "my-gcp-project"\nregion     = "us-central1"' : 'region = "us-east-1"';
  return `# Copy to terraform.tfvars and adjust.\n${region}\n\nimage_tags = {\n${tags}\n}\n`;
}

/** Variables documented in the result (kept in sync with the generated variables.tf). */
function variableList(provider: IacProvider): IacVariable[] {
  const base: IacVariable[] = [
    { name: 'project', type: 'string', description: 'Resource name prefix' },
    { name: 'environment', type: 'string', description: 'Environment name' },
    { name: 'image_tags', type: 'map(string)', description: 'Image tag per service' },
    { name: 'default_image_tag', type: 'string', description: 'Tag for services missing from image_tags' },
  ];
  if (provider === 'aws') return [...base, { name: 'region', type: 'string', description: 'AWS region' }];
  if (provider === 'azure') return [...base, { name: 'location', type: 'string', description: 'Azure location' }];
  return [...base, { name: 'region', type: 'string', description: 'GCP region' }, { name: 'project_id', type: 'string', description: 'GCP project id' }];
}

export function parseProvider(value: string): IacProvider {
  if ((IAC_PROVIDERS as string[]).includes(value)) return value as IacProvider;
  throw new IacError('IAC_ERROR', `Unknown provider "${value}". Expected one of: ${IAC_PROVIDERS.join(', ')}`);
}

/** Render the Terraform files in memory (no filesystem writes). */
export function renderIac(provider: IacProvider, model: IacModel): IacFile[] {
  const files = provider === 'aws' ? generateAws(model) : provider === 'azure' ? generateAzure(model) : generateGcp(model);
  files.push({ path: 'terraform.tfvars.example', content: tfvarsExample(provider, model) });
  files.push({ path: 'README.md', content: readme(provider, model) });
  return files;
}

/**
 * Generate Terraform for the workspace services on one cloud provider.
 *
 * @throws {IacError} for an unknown provider/service, a missing workspace, or a missing `out` (when not a dry run).
 */
export function generateIac(options: GenerateIacOptions): GenerateIacResult {
  const provider = parseProvider(options.provider);
  const cwd = options.cwd ?? process.cwd();
  let ws;
  try {
    ws = loadWorkspace(cwd, options.configPath);
  } catch (err) {
    if (err instanceof WorkspaceLoadError) {
      throw new IacError(err.kind === 'not-found' ? 'WORKSPACE_NOT_FOUND' : 'SCHEMA_VALIDATION_ERROR', err.message);
    }
    throw err;
  }
  let model: IacModel;
  try {
    model = buildIacModel(ws, options.services);
  } catch (err) {
    throw new IacError('IAC_ERROR', (err as Error).message);
  }
  if (!options.dryRun && !options.out) {
    throw new IacError('IAC_ERROR', '--out <dir> is required (or use --dry-run)');
  }

  const warnings: string[] = [];
  const { cyclic } = resolveEnvRefs(model.services);
  for (const c of cyclic) {
    warnings.push(`Circular service reference ${c}: left as a literal value (Terraform cannot express a dependency cycle)`);
  }
  if (provider === 'azure') {
    for (const s of model.services) {
      for (const [k, val] of Object.entries(s.env)) {
        const m = /^[a-z][a-z0-9+.-]*:\/\/([a-z0-9][a-z0-9-]*)/.exec(val);
        const target = m && model.services.find(x => x.name === m[1]);
        if (target && target.type === 'worker') {
          warnings.push(`${s.name}.${k} points at worker "${target.name}" which has no ingress on Container Apps`);
        }
      }
    }
  }
  if (provider === 'aws' && model.services.some(s => s.exposed)) {
    warnings.push('Exposed services are routed by path prefix (/<service>/*) on the shared ALB; applications must serve under that prefix or strip it');
  }

  const rendered = renderIac(provider, model);
  const files: GeneratedFile[] = rendered.map(f => ({ path: f.path, bytes: Buffer.byteLength(f.content), content: f.content }));
  const outDir = options.out ? path.resolve(cwd, options.out) : null;

  let written = false;
  if (!options.dryRun && outDir) {
    fs.mkdirSync(outDir, { recursive: true });
    for (const f of files) fs.writeFileSync(path.join(outDir, f.path), f.content);
    written = true;
  }

  return {
    provider,
    target: TARGETS[provider],
    outDir,
    dryRun: Boolean(options.dryRun),
    written,
    services: model.services.map(s => ({ name: s.name, port: s.port, exposed: s.exposed })),
    files,
    variables: variableList(provider),
    warnings,
  };
}
