// Spec-driven bridge generation: contract IR -> a self-contained bundle of
// per-language client packages plus a copy of the provider's own contract.

import * as fs from 'fs';
import * as path from 'path';

import { ALL_LANGUAGES, contractFileName, type ClientFile, type ClientLanguage } from './codegen/common';
import { generateGoClient, goModulePath } from './codegen/go';
import { generatePythonClient, pyPackageName } from './codegen/python';
import { generateTsClient } from './codegen/ts';
import { toPascal } from './naming';
import { BridgeSpecError } from './spec/errors';
import type { ServiceContract } from './spec/ir';
import { BRIDGE_MARKER } from './spec/discover';

/** Options for {@link buildBridgeBundle}. */
export interface BridgeBundleOptions {
  /** Workspace service name the client talks to (the provider). */
  serviceName: string;
  contract: ServiceContract;
  /** Languages to emit (default: ts, python, go). */
  languages?: ClientLanguage[];
  goModule?: string;
}

/** A generated bundle (not yet written). */
export interface BridgeBundle {
  serviceName: string;
  protocol: ServiceContract['protocol'];
  languages: ClientLanguage[];
  files: ClientFile[];
  warnings: string[];
  /** Root-relative path of the contract copy. */
  contractFile: string;
  /** gRPC only: details needed to compile protobuf stubs. */
  grpc?: { protoFile: string; pyPackage: string; pbModule: string; goModule: string };
}

/** Parse a comma-separated `--lang` list. */
export function parseLanguages(value: string | string[] | undefined): ClientLanguage[] {
  if (!value || (Array.isArray(value) && value.length === 0)) return [...ALL_LANGUAGES];
  const raw = (Array.isArray(value) ? value : value.split(',')).map(v => v.trim().toLowerCase()).filter(Boolean);
  const out: ClientLanguage[] = [];
  for (const item of raw) {
    const lang = item === 'typescript' || item === 'javascript' || item === 'js' ? 'ts' : item === 'py' ? 'python' : item === 'golang' ? 'go' : item;
    if (lang !== 'ts' && lang !== 'python' && lang !== 'go') {
      throw new BridgeSpecError(`Unsupported client language "${item}" (expected ts, python, go)`);
    }
    if (!out.includes(lang)) out.push(lang);
  }
  return out;
}

/** Map a workspace service language to a client language, when there is one. */
export function clientLanguageFor(serviceLanguage: string | undefined): ClientLanguage | undefined {
  switch ((serviceLanguage ?? '').toLowerCase()) {
    case 'typescript':
    case 'javascript':
    case 'deno':
    case 'bun':
      return 'ts';
    case 'python':
      return 'python';
    case 'go':
      return 'go';
    default:
      return undefined;
  }
}

function contractKind(contract: ServiceContract): ClientFile['kind'] {
  return contract.protocol === 'grpc' ? 'proto' : contract.protocol === 'graphql' ? 'graphql-sdl' : 'openapi';
}

function readme(bundle: Omit<BridgeBundle, 'files' | 'warnings'>, contract: ServiceContract): string {
  const lines = [
    `# ${toPascal(bundle.serviceName)} service bridge (${contract.protocol})`,
    '',
    `Generated by \`re-shell service bridge generate\` from **${path.basename(contract.source.path)}** (sha256 \`${contract.source.sha256.slice(0, 12)}\`).`,
    `${contract.operations.length} operation(s), ${contract.models.length} model(s). Do not edit: re-run the generator instead.`,
    '',
    '## Layout',
    '',
    `- \`${bundle.contractFile}\` - the provider's contract (source of truth, used by \`re-shell service validate\`).`,
  ];
  if (bundle.languages.includes('ts')) lines.push('- `ts/` - typed TypeScript client (`npm run build` type-checks it).');
  if (bundle.languages.includes('python')) lines.push('- `python/` - typed Python client package (`pip install ./python`).');
  if (bundle.languages.includes('go')) lines.push('- `go/` - typed Go client module (`go build ./...`).');
  if (bundle.grpc) {
    lines.push(
      '- `generate-stubs.sh` - compiles the protobuf stubs the Python and Go clients import.',
      '',
      '## gRPC stubs',
      '',
      'The TypeScript client loads the `.proto` at runtime (`@grpc/proto-loader`). The Python and Go',
      'clients wrap protoc-generated stubs: run `./generate-stubs.sh` (needs `grpcio-tools` for Python;',
      '`protoc-gen-go` and `protoc-gen-go-grpc` for Go), or pass `--compile-stubs` to the generator.'
    );
  }
  return lines.join('\n') + '\n';
}

function stubScript(bundle: BridgeBundle): string {
  const g = bundle.grpc!;
  const lines = [
    '#!/usr/bin/env sh',
    '# Compile the protobuf stubs imported by the Python and Go clients.',
    'set -eu',
    'cd "$(dirname "$0")"',
    'PROTOC="${PROTOC:-python3 -m grpc_tools.protoc}"',
  ];
  if (bundle.languages.includes('python')) {
    lines.push(
      `mkdir -p python/${g.pyPackage}`,
      `$PROTOC -I. --python_out=python/${g.pyPackage} --pyi_out=python/${g.pyPackage} --grpc_python_out=python/${g.pyPackage} ${g.protoFile}`,
      `sed -i.bak -E 's/^import ([A-Za-z0-9_]+_pb2) as/from . import \\1 as/' python/${g.pyPackage}/*_pb2_grpc.py && rm -f python/${g.pyPackage}/*.bak`
    );
  }
  if (bundle.languages.includes('go')) {
    lines.push(
      '# needs protoc-gen-go and protoc-gen-go-grpc on PATH (go install google.golang.org/protobuf/cmd/protoc-gen-go@latest ...)',
      'mkdir -p go/pb',
      `$PROTOC -I. --go_out=go/pb --go_opt=paths=source_relative,M${g.protoFile}=${g.goModule}/pb --go-grpc_out=go/pb --go-grpc_opt=paths=source_relative,M${g.protoFile}=${g.goModule}/pb ${g.protoFile}`,
      '(cd go && go mod tidy)'
    );
  }
  return lines.join('\n') + '\n';
}

/**
 * Build the in-memory client bundle for a provider contract.
 *
 * @throws BridgeSpecError when the contract has no operations to bridge.
 */
export function buildBridgeBundle(options: BridgeBundleOptions): BridgeBundle {
  const { contract, serviceName } = options;
  const languages = options.languages?.length ? options.languages : [...ALL_LANGUAGES];
  if (contract.operations.length === 0) {
    throw new BridgeSpecError(`${path.basename(contract.source.path)} defines no operations; there is nothing to generate a client for`);
  }
  const gen = { serviceName, goModule: options.goModule };
  const files: ClientFile[] = [];
  const warnings = [...contract.warnings];

  // Contract copy (verbatim bytes of the provider's own spec).
  const contractFile = contractFileName(contract, serviceName);
  files.push({ path: contractFile, content: fs.readFileSync(contract.source.path, 'utf8'), kind: contractKind(contract) });

  let grpc: BridgeBundle['grpc'];
  if (contract.protocol === 'grpc') {
    const pbModule = contractFile.replace(/\.proto$/, '').replace(/[^A-Za-z0-9_]/g, '_');
    grpc = {
      protoFile: contractFile,
      pyPackage: pyPackageName(serviceName),
      pbModule,
      goModule: goModulePath(serviceName, options.goModule),
    };
    // Local imports are copied alongside so protoc / proto-loader can resolve them.
    const baseDir = path.dirname(contract.source.path);
    for (const imp of contract.imports ?? []) {
      const rel = path.relative(baseDir, imp);
      if (rel.startsWith('..')) {
        warnings.push(`imported proto ${imp} is outside the spec directory and was not copied`);
        continue;
      }
      files.push({ path: rel.split(path.sep).join('/'), content: fs.readFileSync(imp, 'utf8'), kind: 'proto' });
    }
  }

  if (languages.includes('ts')) {
    files.push(...generateTsClient(contract, gen, contractFile));
    if (contract.protocol === 'grpc') {
      files.push({ path: `ts/${contractFile}`, content: fs.readFileSync(contract.source.path, 'utf8'), kind: 'support' });
      const baseDir = path.dirname(contract.source.path);
      for (const imp of contract.imports ?? []) {
        const rel = path.relative(baseDir, imp);
        if (!rel.startsWith('..')) files.push({ path: `ts/${rel.split(path.sep).join('/')}`, content: fs.readFileSync(imp, 'utf8'), kind: 'support' });
      }
    }
  }
  if (languages.includes('python')) {
    files.push(...generatePythonClient(contract, gen, grpc?.pbModule));
  }
  if (languages.includes('go')) {
    files.push(...generateGoClient(contract, gen));
  }

  const bundle: BridgeBundle = {
    serviceName,
    protocol: contract.protocol,
    languages,
    files,
    warnings,
    contractFile,
    grpc,
  };
  files.push({ path: 'README.md', content: readme(bundle, contract), kind: 'readme' });
  if (grpc) {
    files.push({ path: 'generate-stubs.sh', content: stubScript(bundle), kind: 'support' });
  }
  files.push({
    path: BRIDGE_MARKER,
    content:
      JSON.stringify(
        {
          generator: 're-shell service bridge',
          service: serviceName,
          protocol: contract.protocol,
          contract: contractFile,
          contractSha256: contract.source.sha256,
          languages,
        },
        null,
        2
      ) + '\n',
    kind: 'support',
  });
  return bundle;
}

/** Write a bundle under `root`; returns the absolute paths written. Never writes outside `root`. */
export function writeBundle(files: ClientFile[], root: string): string[] {
  const written: string[] = [];
  const base = path.resolve(root);
  for (const file of files) {
    const target = path.resolve(base, file.path);
    if (target !== base && !target.startsWith(base + path.sep)) {
      throw new BridgeSpecError(`refusing to write outside ${base}: ${file.path}`);
    }
    fs.mkdirSync(path.dirname(target), { recursive: true });
    fs.writeFileSync(target, file.content, file.path.endsWith('.sh') ? { mode: 0o755 } : undefined);
    written.push(target);
  }
  return written;
}
