// Shared types for the client generators.

import type { IROperation, IRRestOperation, ServiceContract, TypeRef } from '../spec/ir';

/** Target client languages. */
export type ClientLanguage = 'ts' | 'python' | 'go';

export const ALL_LANGUAGES: ClientLanguage[] = ['ts', 'python', 'go'];

/** Kind tag of one generated file. */
export type ClientFileKind =
  | 'proto'
  | 'openapi'
  | 'graphql-sdl'
  | 'ts-client'
  | 'python-client'
  | 'go-client'
  | 'manifest'
  | 'readme'
  | 'support';

/** A generated file (path relative to the bridge output root). */
export interface ClientFile {
  path: string;
  content: string;
  kind: ClientFileKind;
}

/** Inputs shared by every language generator. */
export interface GenerateClientOptions {
  /** Service name as in the workspace (kebab-case). */
  serviceName: string;
  /** Overrides for naming, e.g. Go module path. */
  goModule?: string;
}

/** Marker banner placed at the top of every generated source file. */
export function banner(contract: ServiceContract, comment: '//' | '#'): string {
  return [
    `${comment} Code generated by re-shell service bridge. DO NOT EDIT.`,
    `${comment} Source: ${contract.source.path.split(/[\\/]/).pop()} (sha256:${contract.source.sha256.slice(0, 12)})`,
    `${comment} Protocol: ${contract.protocol}`,
  ].join('\n');
}

/** Operations of one kind with narrowing. */
export function restOps(contract: ServiceContract): IRRestOperation[] {
  return contract.operations.filter((o): o is IRRestOperation => o.protocol === 'rest');
}

/** Stable key of an operation (used by diff + mock). */
export function opKey(op: IROperation): string {
  if (op.protocol === 'rest') return `${op.method} ${op.path}`;
  if (op.protocol === 'grpc') return `${op.fqService}/${op.method}`;
  return `${op.operation}.${op.field}`;
}

/** Output-root-relative contract filename for a protocol. */
export function contractFileName(contract: ServiceContract, serviceName: string): string {
  const base = contract.source.path.split(/[\\/]/).pop() ?? '';
  if (contract.protocol === 'grpc') return base.endsWith('.proto') ? base : `${serviceName}.proto`;
  if (contract.protocol === 'graphql') return base;
  return base;
}

function renameRef(ref: TypeRef, map: Map<string, string>): TypeRef {
  switch (ref.k) {
    case 'ref':
      return map.has(ref.name) ? { k: 'ref', name: map.get(ref.name)! } : ref;
    case 'list':
      return { ...ref, of: renameRef(ref.of, map) };
    case 'map':
      return { k: 'map', of: renameRef(ref.of, map) };
    default:
      return ref;
  }
}

/**
 * Return a copy of the contract in which any model whose name is in `reserved`
 * is renamed (suffix `Model`), so generated models can never shadow the
 * runtime helpers emitted into the same file.
 */
export function avoidReserved(contract: ServiceContract, reserved: Set<string>): ServiceContract {
  const map = new Map<string, string>();
  const taken = new Set(contract.models.map(m => m.name));
  for (const m of contract.models) {
    if (reserved.has(m.name)) {
      let candidate = `${m.name}Model`;
      while (taken.has(candidate)) candidate += '_';
      map.set(m.name, candidate);
      taken.add(candidate);
    }
  }
  if (map.size === 0) return contract;
  return {
    ...contract,
    models: contract.models.map(m => {
      const name = map.get(m.name) ?? m.name;
      if (m.kind === 'object') {
        return { ...m, name, fields: m.fields.map(f => ({ ...f, type: renameRef(f.type, map) })) };
      }
      if (m.kind === 'union') return { ...m, name, members: m.members.map(x => map.get(x) ?? x) };
      return { ...m, name };
    }),
    operations: contract.operations.map(op => {
      if (op.protocol === 'rest') {
        return {
          ...op,
          params: op.params.map(p => ({ ...p, type: renameRef(p.type, map) })),
          body: op.body ? { ...op.body, type: renameRef(op.body.type, map) } : undefined,
          response: op.response ? { type: renameRef(op.response.type, map) } : undefined,
        };
      }
      if (op.protocol === 'grpc') {
        return { ...op, request: renameRef(op.request, map), response: renameRef(op.response, map) };
      }
      return {
        ...op,
        args: op.args.map(a => ({ ...a, type: renameRef(a.type, map) })),
        returns: renameRef(op.returns, map),
      };
    }),
  };
}
