import { roleList, permissionList } from './rbac-fixtures';

/**
 * Builds the RBAC config object for the `security rbac` command.
 * Extracted verbatim from the former monolithic security.group.ts to keep
 * the command module under the 800-line limit. The returned shape is the
 * argument to displayRBACConfig/writeRBACFiles in ../../utils/rbac-manager.
 */
export function buildRbacConfig(
  name: string,
  providers: ('aws' | 'azure' | 'gcp')[],
  options: Record<string, any>
) {
  const finalConfig = {
      projectName: name,
      providers,
      settings: {
        enableFineGrained: options.fineGrained || false,
        defaultDenyAll: options.defaultDeny || true,
        requireMFAForAdmin: options.requireMfa || true,
        enableSessionTimeout: options.sessionTimeout > 0,
        sessionTimeoutMinutes: parseInt(options.sessionTimeout),
        enablePermissionCaching: options.enableCache || true,
        cacheTTLMinutes: parseInt(options.cacheTtl),
        enableAuditLogging: options.enableAudit || true,
        logRetentionDays: parseInt(options.auditRetention),
        enableDynamicPermissions: false,
        enableRoleHierarchy: options.enableHierarchy || false,
        maxRoleDepth: parseInt(options.maxDepth),
        enableTemporaryAccess: options.enableTemporary || false,
        temporaryAccessMaxHours: parseInt(options.tempMaxHours),
        enableIPRestrictions: options.enableIpRestrictions || false,
        enableTimeRestrictions: options.enableTimeRestrictions || false,
        enableContextAwareAccess: options.enableContextAware || false,
      },
      roles: roleList,
      permissions: permissionList,
      policies: [
        {
          id: 'policy-admin-access',
          name: 'Administrator Access Policy',
          description: 'Policy governing administrator access to system resources',
          status: 'active' as const,
          priority: 1,
          statements: [
            {
              id: 'stmt-admin-allow',
              effect: 'allow' as const,
              principals: [
                { type: 'role' as const, id: 'role-super-admin' },
                { type: 'role' as const, id: 'role-admin' },
              ],
              actions: ['create' as const, 'read' as const, 'update' as const, 'delete' as const, 'admin' as const],
              resources: [
                { type: 'wildcard' as const, pattern: '*' },
              ],
              conditions: [],
              overrideEffect: true,
            },
          ],
          version: '1.0.0',
          createdAt: new Date('2024-01-01'),
          updatedAt: new Date(),
          effectiveFrom: new Date('2024-01-01'),
          metadata: {
            description: 'Grants full access to administrators',
            owner: 'ciso',
            tags: ['admin', 'full-access'],
            complianceReferences: ['SOC-2', 'ISO-27001'],
            riskLevel: 'critical' as const,
            changeHistory: [
              { timestamp: new Date('2024-01-01'), user: 'system', action: 'created', reason: 'Initial policy' },
            ],
          },
        },
        {
          id: 'policy-operator-access',
          name: 'Operator Access Policy',
          description: 'Policy for operational access to resources',
          status: 'active' as const,
          priority: 10,
          statements: [
            {
              id: 'stmt-operator-allow',
              effect: 'allow' as const,
              principals: [
                { type: 'role' as const, id: 'role-operator' },
              ],
              actions: ['read' as const, 'execute' as const],
              resources: [
                { type: 'prefix' as const, pattern: '/services/*' },
                { type: 'exact' as const, pattern: '/api/health' },
              ],
              conditions: [
                { type: 'string' as const, operator: 'equals', key: 'environment', value: 'production' },
              ],
            },
          ],
          version: '1.0.0',
          createdAt: new Date('2024-01-15'),
          updatedAt: new Date(),
          effectiveFrom: new Date('2024-01-15'),
          metadata: {
            description: 'Grants operational access for service monitoring',
            owner: 'ops-manager',
            tags: ['operations', 'read-only'],
            complianceReferences: [],
            riskLevel: 'low' as const,
            changeHistory: [
              { timestamp: new Date('2024-01-15'), user: 'ops-manager', action: 'created', reason: 'Operations workflow' },
            ],
          },
        },
      ],
      assignments: [
        {
          id: 'assign-001',
          userId: 'user-admin-001',
          roleId: 'role-super-admin',
          status: 'active' as const,
          assignedBy: 'system',
          assignedAt: new Date('2024-01-01'),
          conditions: [],
          context: { source: 'direct' as const, reason: 'Initial super admin' },
          isTemporary: false,
          requiresApproval: true,
          approvedBy: 'ceo',
          approvedAt: new Date('2024-01-01'),
        },
        {
          id: 'assign-002',
          userId: 'user-admin-002',
          roleId: 'role-admin',
          status: 'active' as const,
          assignedBy: 'user-admin-001',
          assignedAt: new Date('2024-01-15'),
          conditions: [],
          context: { source: 'direct' as const, reason: 'IT Administrator' },
          isTemporary: false,
          requiresApproval: false,
        },
        {
          id: 'assign-003',
          userId: 'user-operator-001',
          roleId: 'role-operator',
          status: 'active' as const,
          assignedBy: 'user-admin-002',
          assignedAt: new Date('2024-02-01'),
          expiresAt: new Date(Date.now() + 365 * 24 * 60 * 60 * 1000),
          conditions: [
            { type: 'time' as const, field: 'hour', operator: 'between', value: [8, 18] },
          ],
          context: { source: 'direct' as const, reason: 'Operations team member' },
          isTemporary: false,
          requiresApproval: false,
        },
        {
          id: 'assign-004',
          userId: 'user-dev-001',
          roleId: 'role-developer',
          status: 'active' as const,
          assignedBy: 'user-admin-002',
          assignedAt: new Date('2024-02-15'),
          conditions: [],
          context: { source: 'direct' as const, reason: 'Development team member', ticketId: 'REQ-12345' },
          isTemporary: false,
          requiresApproval: false,
        },
        {
          id: 'assign-005',
          userId: 'user-viewer-001',
          roleId: 'role-viewer',
          status: 'active' as const,
          assignedBy: 'user-admin-002',
          assignedAt: new Date('2024-03-01'),
          conditions: [],
          context: { source: 'direct' as const, reason: 'Executive dashboard access' },
          isTemporary: false,
          requiresApproval: false,
        },
      ],
      groups: [
        {
          id: 'group-administrators',
          name: 'Administrators',
          description: 'System administrators group',
          type: 'department' as const,
          status: 'active' as const,
          members: ['user-admin-001', 'user-admin-002'],
          roles: ['role-admin'],
          inheritsFrom: [],
          owners: ['user-admin-001'],
          metadata: {
            category: 'administration',
            department: 'IT',
            costCenter: 'CC-001',
            location: 'HQ',
            externalSync: true,
            syncSource: 'LDAP',
            lastSyncedAt: new Date(),
          },
          createdAt: new Date('2024-01-01'),
          updatedAt: new Date(),
        },
        {
          id: 'group-operations',
          name: 'Operations Team',
          description: 'Operations and DevOps engineers',
          type: 'team' as const,
          status: 'active' as const,
          members: ['user-operator-001'],
          roles: ['role-operator'],
          inheritsFrom: [],
          owners: ['user-admin-002'],
          metadata: {
            category: 'operations',
            department: 'Operations',
            costCenter: 'CC-002',
            externalSync: false,
          },
          createdAt: new Date('2024-01-15'),
          updatedAt: new Date(),
        },
        {
          id: 'group-development',
          name: 'Development Team',
          description: 'Software developers',
          type: 'team' as const,
          status: 'active' as const,
          members: ['user-dev-001'],
          roles: ['role-developer'],
          inheritsFrom: [],
          owners: ['user-admin-002'],
          metadata: {
            category: 'development',
            department: 'Engineering',
            costCenter: 'CC-003',
            externalSync: true,
            syncSource: 'Okta',
            lastSyncedAt: new Date(),
          },
          createdAt: new Date('2024-02-01'),
          updatedAt: new Date(),
        },
      ],
      resourceHierarchy: [
        {
          id: 'resource-root',
          name: 'System Root',
          type: 'root',
          path: '/',
          permissions: ['perm-admin-all'],
          children: ['resource-organization'],
          metadata: {
            owner: 'system',
            classification: 'restricted' as const,
            tags: ['system', 'root'],
            complianceRequirements: [],
            createdAt: new Date('2024-01-01'),
            updatedAt: new Date(),
          },
        },
        {
          id: 'resource-organization',
          name: 'Organization Resources',
          type: 'organization',
          parentId: 'resource-root',
          path: '/org',
          permissions: ['perm-resources-read'],
          children: ['resource-production', 'resource-development'],
          metadata: {
            owner: 'c-level',
            classification: 'confidential' as const,
            tags: ['organization'],
            complianceRequirements: ['SOC-2'],
            createdAt: new Date('2024-01-01'),
            updatedAt: new Date(),
          },
        },
        {
          id: 'resource-production',
          name: 'Production Environment',
          type: 'environment',
          parentId: 'resource-organization',
          path: '/org/production',
          permissions: ['perm-admin-all', 'perm-resources-manage'],
          children: ['resource-prod-services'],
          metadata: {
            owner: 'ops-manager',
            classification: 'confidential' as const,
            tags: ['production', 'critical'],
            complianceRequirements: ['SOC-2', 'ISO-27001', 'PCI-DSS'],
            createdAt: new Date('2024-01-01'),
            updatedAt: new Date(),
          },
        },
        {
          id: 'resource-development',
          name: 'Development Environment',
          type: 'environment',
          parentId: 'resource-organization',
          path: '/org/development',
          permissions: ['perm-resources-create', 'perm-resources-update', 'perm-services-deploy'],
          children: ['resource-dev-services'],
          metadata: {
            owner: 'engineering-manager',
            classification: 'internal' as const,
            tags: ['development', 'sandbox'],
            complianceRequirements: [],
            createdAt: new Date('2024-01-01'),
            updatedAt: new Date(),
          },
        },
      ],
      auditLogs: [
        {
          id: 'audit-001',
          timestamp: new Date(Date.now() - 60 * 60 * 1000),
          userId: 'user-admin-001',
          action: 'create',
          resource: '/users/user-operator-001',
          resourceType: 'users',
          outcome: 'allowed' as const,
          reason: 'User creation approved',
          ipAddress: '10.0.1.100',
          userAgent: 'Mozilla/5.0',
          sessionContext: {
            sessionId: 'sess-12345',
            mfaVerified: true,
            sessionAge: 1800,
            loginTime: new Date(Date.now() - 60 * 60 * 1000),
            lastActivity: new Date(),
          },
          policyEvaluated: 'policy-admin-access',
          rolesUsed: ['role-super-admin'],
          permissionsChecked: ['perm-users-write'],
        },
        {
          id: 'audit-002',
          timestamp: new Date(Date.now() - 30 * 60 * 1000),
          userId: 'user-operator-001',
          action: 'read',
          resource: '/services/api-status',
          resourceType: 'services',
          outcome: 'allowed' as const,
          ipAddress: '10.0.2.50',
          userAgent: 'curl/7.68.0',
          sessionContext: {
            sessionId: 'sess-12346',
            mfaVerified: false,
            sessionAge: 900,
            loginTime: new Date(Date.now() - 30 * 60 * 1000),
            lastActivity: new Date(),
          },
          policyEvaluated: 'policy-operator-access',
          rolesUsed: ['role-operator'],
          permissionsChecked: ['perm-services-execute'],
        },
        {
          id: 'audit-003',
          timestamp: new Date(Date.now() - 15 * 60 * 1000),
          userId: 'user-viewer-001',
          action: 'delete',
          resource: '/users/user-dev-001',
          resourceType: 'users',
          outcome: 'denied' as const,
          reason: 'Insufficient permissions for delete action',
          ipAddress: '10.0.3.75',
          userAgent: 'Mozilla/5.0',
          sessionContext: {
            sessionId: 'sess-12347',
            mfaVerified: false,
            sessionAge: 300,
            loginTime: new Date(Date.now() - 15 * 60 * 1000),
            lastActivity: new Date(),
          },
          policyEvaluated: 'policy-admin-access',
          rolesUsed: ['role-viewer'],
          permissionsChecked: ['perm-dashboard-read'],
        },
      ],
  };
  return finalConfig;
}
