import { vendorList, assessmentList } from './vendor-fixtures';

/**
 * Builds the vendor-assessment config for the `security vendor` command.
 * Extracted verbatim from the former monolithic security.group.ts to keep
 * the command module under the 800-line limit. The returned shape is the
 * argument to displayVendorConfig/writeVendorFiles in ../../utils/vendor-assessment.
 */
export function buildVendorConfig(
  name: string,
  providers: Array<'aws' | 'azure' | 'gcp'>,
  options: Record<string, any>
) {
  const finalConfig = {
      projectName: name,
      providers,
      settings: {
        autoAssessment: options.autoAssess === true,
        assessmentFrequency: options.assessmentFrequency,
        requireApproval: true,
        approvers: ['ciso', 'procurement-manager', 'legal-counsel'],
        riskThreshold: parseInt(options.riskThreshold),
        enableContinuousMonitoring: options.enableMonitoring === true,
        monitoringInterval: parseInt(options.monitoringInterval),
        enableQuestionnaires: options.enableQuestionnaires === true,
        questionnaireTemplate: options.questionnaireTemplate,
        enableScorecards: options.enableScorecards !== false,
        scorecardWeighting: {
          securityPosture: 30,
          complianceCertifications: 20,
          financialHealth: 15,
          operationalMaturity: 10,
          incidentHistory: 10,
          contractTerms: 5,
          dataProtection: 5,
          serviceLevelAgreement: 5,
        },
        enableFindings: options.enableFindings !== false,
        findingRetentionDays: parseInt(options.findingRetention),
        enableAuditLogging: true,
        notifyFindings: true,
        notificationChannels: ['email' as const, 'slack' as const],
        enableBenchmarking: options.enableBenchmarking === true,
        benchmarkIndustry: options.benchmarkIndustry,
        requireContractReview: true,
        contractReviewFrequency: options.assessmentFrequency,
        enableIncidentTracking: true,
        incidentRetentionDays: 2555,
        requireSoc2: options.requireSoc2 === true,
        requireIso27001: options.requireIso27001 === true,
        requireHipaa: options.requireHipaa === true,
        requirePciDss: options.requirePcidss === true,
        requireGdpr: options.requireGdpr === true,
        customRequirements: [],
      },
      vendors: vendorList,
      assessments: assessmentList,
      scorecards: [
        {
          id: 'scorecard-001',
          vendorId: 'vendor-001',
          vendorName: 'CloudInfrastructure Provider',
          period: '2024-Q4',
          status: 'approved' as const,
          generatedDate: new Date('2024-12-10'),
          generatedBy: 'vendor-management-team',
          reviewedBy: 'ciso',
          reviewedDate: new Date('2024-12-12'),
          approvedBy: 'ciso',
          approvedDate: new Date('2024-12-15'),
          overallScore: 85,
          rating: 'low' as const,
          categories: [
            {
              name: 'Security Posture',
              weight: 30,
              score: 88,
              weightedScore: 26,
              status: 'good' as const,
              comments: 'Strong security controls with minor improvements needed',
            },
            {
              name: 'Compliance Certifications',
              weight: 20,
              score: 95,
              weightedScore: 19,
              status: 'excellent' as const,
              comments: 'Excellent certification coverage - SOC 2, ISO 27001 valid',
            },
            {
              name: 'Financial Health',
              weight: 15,
              score: 90,
              weightedScore: 14,
              status: 'excellent' as const,
              comments: 'Strong financial position, public company',
            },
            {
              name: 'Operational Maturity',
              weight: 10,
              score: 82,
              weightedScore: 8,
              status: 'good' as const,
              comments: 'Mature processes and procedures',
            },
            {
              name: 'Incident History',
              weight: 10,
              score: 85,
              weightedScore: 9,
              status: 'good' as const,
              comments: 'Few incidents, good response',
            },
            {
              name: 'Contract Terms',
              weight: 5,
              score: 70,
              weightedScore: 4,
              status: 'satisfactory' as const,
              comments: 'Standard terms, some limitations',
            },
            {
              name: 'Data Protection',
              weight: 5,
              score: 90,
              weightedScore: 5,
              status: 'excellent' as const,
              comments: 'Strong data protection controls',
            },
            {
              name: 'Service Level Agreement',
              weight: 5,
              score: 90,
              weightedScore: 5,
              status: 'excellent' as const,
              comments: 'Exceeds SLA commitments consistently',
            },
          ],
          trend: 'stable' as const,
          trendScore: 2,
          benchmarkComparison: {
            industryAverage: 72,
            percentile: 85,
            rank: 'Top 15%',
            peers: 150,
          },
          recommendations: [
            'Continue monitoring incident response capabilities',
            'Review contract terms for next renewal',
          ],
          strengths: [
            'Strong security posture and controls',
            'Comprehensive compliance certifications',
            'Excellent financial health',
            'High availability and performance',
          ],
          weaknesses: [
            'Limited liability caps in contract',
            'Some regions lack data residency options',
          ],
          actionItems: [
            {
              id: 'action-001',
              description: 'Review contract liability terms for next renewal',
              priority: 'medium' as const,
              assignedTo: 'legal-counsel',
              dueDate: new Date('2025-01-15'),
              status: 'pending' as const,
            },
          ],
        },
        {
          id: 'scorecard-002',
          vendorId: 'vendor-002',
          vendorName: 'Payment Gateway Service',
          period: '2024-Q4',
          status: 'approved' as const,
          generatedDate: new Date('2024-11-20'),
          generatedBy: 'vendor-management-team',
          reviewedBy: 'finance-director',
          reviewedDate: new Date('2024-11-25'),
          approvedBy: 'ciso',
          approvedDate: new Date('2024-11-28'),
          overallScore: 68,
          rating: 'medium' as const,
          categories: [
            {
              name: 'Security Posture',
              weight: 30,
              score: 72,
              weightedScore: 22,
              status: 'satisfactory' as const,
              comments: 'Adequate security with room for improvement',
            },
            {
              name: 'Compliance Certifications',
              weight: 20,
              score: 90,
              weightedScore: 18,
              status: 'excellent' as const,
              comments: 'PCI DSS compliant with valid certification',
            },
            {
              name: 'Financial Health',
              weight: 15,
              score: 70,
              weightedScore: 11,
              status: 'satisfactory' as const,
              comments: 'Private company with reasonable financials',
            },
            {
              name: 'Operational Maturity',
              weight: 10,
              score: 75,
              weightedScore: 8,
              status: 'satisfactory' as const,
              comments: 'Developing operational maturity',
            },
            {
              name: 'Incident History',
              weight: 10,
              score: 50,
              weightedScore: 5,
              status: 'needs-improvement' as const,
              comments: 'Recent service outage incident',
            },
            {
              name: 'Contract Terms',
              weight: 5,
              score: 75,
              weightedScore: 4,
              status: 'satisfactory' as const,
              comments: 'Good terms with appropriate penalties',
            },
            {
              name: 'Data Protection',
              weight: 5,
              score: 85,
              weightedScore: 4,
              status: 'good' as const,
              comments: 'Strong PCI DSS compliance',
            },
            {
              name: 'Service Level Agreement',
              weight: 5,
              score: 60,
              weightedScore: 3,
              status: 'needs-improvement' as const,
              comments: 'SLA misses in recent quarter',
            },
          ],
          trend: 'declining' as const,
          trendScore: -5,
          recommendations: [
            'Implement backup payment gateway urgently',
            'Monitor SLA performance closely',
            'Review incident response procedures',
          ],
          strengths: [
            'PCI DSS compliant',
            'Strong data protection',
            'Good contract terms',
          ],
          weaknesses: [
            'Recent service outage',
            'SLA performance degradation',
            'Single point of dependency',
          ],
          actionItems: [
            {
              id: 'action-002',
              description: 'Evaluate and onboard backup payment gateway',
              priority: 'critical' as const,
              assignedTo: 'finance-director',
              dueDate: new Date('2025-01-31'),
              status: 'in-progress' as const,
            },
            {
              id: 'action-003',
              description: 'Review SLA performance penalties',
              priority: 'high' as const,
              assignedTo: 'legal-counsel',
              dueDate: new Date('2024-12-31'),
              status: 'pending' as const,
            },
          ],
        },
      ],
      questionnaires: [],
      findings: [
        {
          id: 'finding-001',
          vendorId: 'vendor-001',
          vendorName: 'CloudInfrastructure Provider',
          assessmentId: 'assessment-001',
          title: 'Incident Response Documentation Gap',
          description: 'Incident response procedures lack detailed documentation for certain scenarios',
          severity: 'low' as const,
          category: 'operational' as const,
          status: 'open' as const,
          discoveredDate: new Date('2024-12-01'),
          discoveredBy: 'security-team',
          dueDate: new Date('2025-01-15'),
          remediation: 'Vendor to provide detailed incident response documentation for all identified scenarios',
          assignedTo: 'vendor-management-team',
          progress: 0,
          lastUpdated: new Date('2024-12-01'),
          updatedBy: 'security-team',
          impact: 'Low impact - existing procedures are adequate but documentation gaps exist',
          references: ['assessment-001-domain-003'],
          resolutions: [],
        },
        {
          id: 'finding-002',
          vendorId: 'vendor-002',
          vendorName: 'Payment Gateway Service',
          assessmentId: 'assessment-002',
          title: 'Network Security Control Gaps',
          description: 'Network security controls do not meet best practice standards for payment processing',
          severity: 'medium' as const,
          category: 'security' as const,
          status: 'in-progress' as const,
          discoveredDate: new Date('2024-11-15'),
          discoveredBy: 'security-team',
          dueDate: new Date('2025-01-31'),
          remediation: 'Vendor to implement enhanced network security controls including DDoS protection and WAF',
          assignedTo: 'vendor-management-team',
          progress: 40,
          lastUpdated: new Date('2024-12-10'),
          updatedBy: 'vendor-management-team',
          impact: 'Medium impact - increased risk of network-based attacks',
          references: ['assessment-002-domain-005'],
          resolutions: [
            {
              date: new Date('2024-12-10'),
              action: 'Vendor submitted remediation plan',
              performedBy: 'vendor-management-team',
              notes: 'Plan approved, implementation in progress',
              evidence: ['remediation-plan-002'],
            },
          ],
        },
        {
          id: 'finding-003',
          vendorId: 'vendor-002',
          vendorName: 'Payment Gateway Service',
          assessmentId: 'assessment-002',
          title: 'Single Point of Failure',
          description: 'No backup payment gateway provider identified - creates single point of failure',
          severity: 'high' as const,
          category: 'operational' as const,
          status: 'open' as const,
          discoveredDate: new Date('2024-11-15'),
          discoveredBy: 'finance-director',
          dueDate: new Date('2025-02-28'),
          remediation: 'Identify and onboard secondary payment gateway provider for redundancy',
          assignedTo: 'finance-director',
          progress: 25,
          lastUpdated: new Date('2024-12-15'),
          updatedBy: 'finance-director',
          impact: 'High impact - payment processing outage could impact revenue',
          references: ['incident-001'],
          resolutions: [],
        },
      ],
      reviews: [],
      approvals: [],
      contracts: [
        {
          id: 'contract-001',
          vendorId: 'vendor-001',
          vendorName: 'CloudInfrastructure Provider',
          contractType: 'msa' as const,
          contractNumber: 'MSA-2020-001',
          startDate: new Date('2020-01-15'),
          endDate: undefined,
          renewalDate: new Date('2025-01-15'),
          autoRenew: true,
          noticePeriod: 90,
          status: 'active' as const,
          currency: 'USD',
          annualValue: 1200000,
          paymentTerms: 'Net 30',
          terms: {
            confidentiality: 'Standard confidentiality provisions',
            dataProtection: 'Complies with GDPR, data processing agreement in place',
            intellectualProperty: 'Standard IP provisions',
            warranties: 'Standard warranties for services',
            indemnification: 'Mutual indemnification with caps',
            limitationOfLiability: 'Cap at 12 months fees',
            terminationForConvenience: true,
            terminationForCause: true,
            auditRights: true,
            auditFrequency: 'annually',
            subcontractingAllowed: true,
            subcontractConsentRequired: false,
          },
          dataProcessing: true,
          dsaAttached: true,
          slaIncluded: true,
          liability: {
            capType: 'aggregate' as const,
            capAmount: 1200000,
            insuranceRequired: true,
            insuranceTypes: ['Cyber Liability', 'General Liability', 'Professional Liability'],
            minimumInsurance: 10000000,
          },
          reviewFrequency: 'annual' as const,
          nextReview: new Date('2025-01-15'),
          documentUrl: 'https://contracts.example.com/msa-001',
          signedBy: 'CTO',
          signedDate: new Date('2020-01-10'),
          counterpartySignatory: 'Vendor CEO',
          attachments: [],
        },
      ],
      incidents: [
        {
          id: 'incident-001',
          vendorId: 'vendor-002',
          vendorName: 'Payment Gateway Service',
          incidentDate: new Date('2024-10-15'),
          detectedDate: new Date('2024-10-15'),
          reportedDate: new Date('2024-10-16'),
          severity: 'high' as const,
          type: 'service-outage' as const,
          title: 'Payment Gateway Service Outage',
          description: '4-hour service outage affecting payment processing',
          impact: {
            dataAffected: false,
            recordsAffected: undefined,
            customersAffected: 5000,
            systemsAffected: ['payment-api', 'checkout-service'],
            servicesAffected: ['payment-processing'],
            duration: 4,
            financialImpact: 50000,
            reputationImpact: 'medium' as const,
          },
          rootCause: 'Network equipment failure at primary data center',
          containmentActions: [
            'Rerouted traffic to secondary data center',
            'Activated incident response team',
          ],
          remediationActions: [
            'Replaced failed network equipment',
            'Implemented redundant network paths',
          ],
          preventiveActions: [
            'Upgraded network infrastructure',
            'Implemented automated failover',
          ],
          notificationSent: true,
          notificationTimeline: [
            {
              date: new Date('2024-10-15'),
              recipient: 'customers',
              method: 'email' as const,
              content: 'Service outage notification',
              sentBy: 'vendor-support',
            },
          ],
          status: 'resolved' as const,
          assignedTo: 'vendor-management-team',
          resolvedDate: new Date('2024-10-19'),
          lessonsLearned: 'Need for backup payment gateway confirmed',
          references: ['post-mortem-001'],
        },
      ],
  };
  return finalConfig;
}
