import { BackendTemplate } from '../types';

export const freshDenoTemplate: BackendTemplate = {
  id: 'fresh-deno',
  name: 'fresh-deno',
  displayName: 'Fresh (Deno)',
  description: 'Modern full-stack web framework for Deno with SSR and islands architecture',
  language: 'typescript',
  framework: 'fresh',
  version: '1.0.0',
  tags: ['deno', 'fresh', 'typescript', 'rest-api', 'websockets', 'pwa', 'full-stack'],
  port: 8000,
  dependencies: {},
  features: ['authentication', 'validation', 'logging', 'cors', 'documentation', 'rest-api', 'websockets', 'graphql'],

  files: {
    // Import map for Deno
    // Deno configuration
    'deno.json': `{
  "nodeModulesDir": "auto",
  "tasks": {
    "dev": "deno run -A --watch=static/,routes/ dev.ts",
    "build": "deno run -A dev.ts build",
    "start": "deno serve -A _fresh/server.js",
    "test": "deno test -A",
    "check": "deno check"
  },
  "exclude": ["**/_fresh/*"],
  "imports": {
    "fresh": "jsr:@fresh/core@^2.0.0",
    "@fresh/plugin-tailwind": "jsr:@fresh/plugin-tailwind@^0.0.1-alpha.9",
    "preact": "npm:preact@^10.27.1",
    "@preact/signals": "npm:@preact/signals@^2.3.1",
    "tailwindcss": "npm:tailwindcss@^4.1.10",
    "@tailwindcss/postcss": "npm:@tailwindcss/postcss@^4.1.10",
    "postcss": "npm:postcss@^8.5.6",
    "graphql": "npm:graphql@^16.9.0",
    "@std/assert": "jsr:@std/assert@^1.0.0",
    "@std/encoding": "jsr:@std/encoding@^1.0.5"
  },
  "compilerOptions": {
    "lib": ["dom", "dom.asynciterable", "dom.iterable", "deno.ns"],
    "jsx": "precompile",
    "jsxImportSource": "preact",
    "jsxPrecompileSkipElements": [
      "a",
      "img",
      "source",
      "body",
      "html",
      "head",
      "title",
      "meta",
      "script",
      "link",
      "style",
      "base",
      "noscript",
      "template"
    ]
  }
}
`,

    // Main entry point (auto-generated by Fresh)
    'main.ts': `import { App, staticFiles } from "fresh";
import { type State } from "./state.ts";
import { db } from "./db.ts";

export const app = new App<State>();

// Seed the in-memory database (default admin user and sample products)
await db.initialize();

app.use(staticFiles());

// File-system routes: routes/**
app.fsRoutes();
`,

    // Fresh configuration
    // Configuration
    'config.ts': `const config = {
  port: Number(Deno.env.get("PORT")) || 8000,
  environment: Deno.env.get("DENO_ENVIRONMENT") || "development",

  // JWT
  jwtSecret: Deno.env.get("JWT_SECRET") || "change-this-secret-in-production",
  jwtExpiration: Deno.env.get("JWT_EXPIRATION") || "7d",

  // Database
  dbPath: Deno.env.get("DB_PATH") || "./data/db.json"};

export { config };
`,

    // Database (in-memory)
    'db.ts': `import { config } from "./config.ts";

interface User {
  id: string;
  email: string;
  password: string;
  name: string;
  role: "user" | "admin";
  createdAt: string;
  updatedAt: string;
}

interface Product {
  id: string;
  name: string;
  description?: string;
  price: number;
  stock: number;
  createdAt: string;
  updatedAt: string;
}

class InMemoryDatabase {
  private users: User[] = [];
  private products: Product[] = [];

  async initialize() {
    console.log("📦 Using in-memory database");

    // Create admin user
    const adminPassword = await this.hashPassword("admin123");
    this.users.push({
      id: crypto.randomUUID(),
      email: "admin@example.com",
      password: adminPassword,
      name: "Admin User",
      role: "admin",
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString()});

    // Create sample products
    this.products.push(
      {
        id: "1",
        name: "Sample Product 1",
        description: "This is a sample product",
        price: 29.99,
        stock: 100,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString()},
      {
        id: "2",
        name: "Sample Product 2",
        description: "Another sample product",
        price: 49.99,
        stock: 50,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString()}
    );

    console.log("✅ Database initialized");
    console.log("👤 Default admin: admin@example.com / admin123");
  }

  private async hashPassword(password: string): Promise<string> {
    const encoder = new TextEncoder();
    const data = encoder.encode(password);
    const hashBuffer = await crypto.subtle.digest("SHA-256", data);
    const hashArray = Array.from(new Uint8Array(hashBuffer));
    return hashArray.map(b => b.toString(16).padStart(2, "0")).join("");
  }

  private async comparePassword(password: string, hash: string): Promise<boolean> {
    const passwordHash = await this.hashPassword(password);
    return passwordHash === hash;
  }

  // Users
  getUsers(): User[] {
    return this.users.map(u => ({ ...u, password: "" }));
  }

  getUserById(id: string): User | undefined {
    const user = this.users.find(u => u.id === id);
    return user ? { ...user, password: "" } : undefined;
  }

  getUserByEmail(email: string): User | undefined {
    return this.users.find(u => u.email === email);
  }

  async createUser(user: Omit<User, "id" | "createdAt" | "updatedAt">): Promise<User> {
    const hashedPassword = await this.hashPassword(user.password);
    const newUser: User = {
      ...user,
      password: hashedPassword,
      id: crypto.randomUUID(),
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString()};
    this.users.push(newUser);
    return { ...newUser, password: "" };
  }

  async verifyUser(email: string, password: string): Promise<User | null> {
    const user = this.users.find(u => u.email === email);
    if (!user) return null;
    const valid = await this.comparePassword(password, user.password);
    if (!valid) return null;
    return { ...user, password: "" };
  }

  updateUser(id: string, updates: Partial<Omit<User, "id" | "createdAt" | "password">>): User | undefined {
    const index = this.users.findIndex(u => u.id === id);
    if (index === -1) return undefined;

    this.users[index] = {
      ...this.users[index],
      ...updates,
      updatedAt: new Date().toISOString()};
    return { ...this.users[index], password: "" };
  }

  deleteUser(id: string): boolean {
    const index = this.users.findIndex(u => u.id === id);
    if (index === -1) return false;
    this.users.splice(index, 1);
    return true;
  }

  // Products
  getProducts(): Product[] {
    return this.products;
  }

  getProductById(id: string): Product | undefined {
    return this.products.find(p => p.id === id);
  }

  createProduct(product: Omit<Product, "id" | "createdAt" | "updatedAt">): Product {
    const newProduct: Product = {
      ...product,
      id: crypto.randomUUID(),
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString()};
    this.products.push(newProduct);
    return newProduct;
  }

  updateProduct(id: string, updates: Partial<Omit<Product, "id" | "createdAt">>): Product | undefined {
    const index = this.products.findIndex(p => p.id === id);
    if (index === -1) return undefined;

    this.products[index] = {
      ...this.products[index],
      ...updates,
      updatedAt: new Date().toISOString()};
    return this.products[index];
  }

  deleteProduct(id: string): boolean {
    const index = this.products.findIndex(p => p.id === id);
    if (index === -1) return false;
    this.products.splice(index, 1);
    return true;
  }
}

export const db = new InMemoryDatabase();
`,

    // JWT utilities
    'utils/jwt.ts': `import { decodeBase64Url, encodeBase64Url } from "@std/encoding/base64url";
import { config } from "../config.ts";

export interface JWTPayload {
  sub: string;
  email: string;
  role: string;
  exp?: number;
}

const encoder = new TextEncoder();
const decoder = new TextDecoder();

function importKey(usage: "sign" | "verify"): Promise<CryptoKey> {
  return crypto.subtle.importKey(
    "raw",
    encoder.encode(config.jwtSecret),
    { name: "HMAC", hash: "SHA-256" },
    false,
    [usage],
  );
}

export async function createToken(payload: Omit<JWTPayload, "exp">): Promise<string> {
  const expiration = Math.floor(Date.now() / 1000) + 7 * 24 * 60 * 60; // 7 days
  const header = encodeBase64Url(JSON.stringify({ alg: "HS256", typ: "JWT" }));
  const body = encodeBase64Url(JSON.stringify({ ...payload, exp: expiration }));
  const data = \`\${header}.\${body}\`;

  const signature = await crypto.subtle.sign("HMAC", await importKey("sign"), encoder.encode(data));
  return \`\${data}.\${encodeBase64Url(signature)}\`;
}

export async function verifyToken(token: string): Promise<JWTPayload | null> {
  try {
    const parts = token.split(".");
    if (parts.length !== 3) return null;

    const [header, body, signature] = parts;
    const valid = await crypto.subtle.verify(
      "HMAC",
      await importKey("verify"),
      decodeBase64Url(signature),
      encoder.encode(\`\${header}.\${body}\`),
    );
    if (!valid) return null;

    const payload = JSON.parse(decoder.decode(decodeBase64Url(body))) as JWTPayload;
    if (payload.exp && payload.exp < Math.floor(Date.now() / 1000)) return null;

    return payload;
  } catch {
    return null;
  }
}
`,

    // Middleware
    'middleware/auth.ts': `import type { State } from "../state.ts";
import { json } from "../utils/http.ts";

// Route guards. Call at the top of a handler and return the result when it is
// not null:
//
//   const denied = requireRole(ctx, "admin");
//   if (denied) return denied;

export function requireAuth(ctx: { state: State }): Response | null {
  if (!ctx.state.user) {
    return json({ error: "Unauthorized" }, 401);
  }
  return null;
}

export function requireRole(ctx: { state: State }, ...roles: string[]): Response | null {
  const denied = requireAuth(ctx);
  if (denied) return denied;
  if (!roles.includes(ctx.state.user!.role)) {
    return json({ error: "Forbidden" }, 403);
  }
  return null;
}
`,

    // Routes - API: Auth
    // Routes - API: Products
    // Routes - API: Users
    // Routes - Health
    'routes/api/health.ts': `import { define } from "../../state.ts";
import { json } from "../../utils/http.ts";

export const handler = define.handlers({
  GET() {
    return json({ status: "healthy", timestamp: new Date().toISOString() });
  },
});
`,

    // GraphQL schema and resolvers
    'src/graphql/schema.ts': `import { GraphQLSchema, GraphQLObjectType, GraphQLString } from "graphql";

export const schema = new GraphQLSchema({
  query: new GraphQLObjectType({
    name: "Query",
    fields: {
      hello: {
        type: GraphQLString,
        resolve: () => "Hello from DenoFresh GraphQL!"
      },
      health: {
        type: GraphQLString,
        resolve: () => "healthy"
      }
    }
  })
});
`,

    // Routes - GraphQL endpoint
    'routes/graphql.ts': `import { graphql } from "graphql";
import { define } from "../state.ts";
import { schema } from "../src/graphql/schema.ts";
import { json } from "../utils/http.ts";

async function execute(source: string): Promise<Response> {
  try {
    return json(await graphql({ schema, source }));
  } catch (error) {
    return json({ errors: [{ message: (error as Error).message }] }, 400);
  }
}

// GET /graphql?query={ hello } and POST /graphql {"query": "{ hello }"}
export const handler = define.handlers({
  GET(ctx) {
    const query = new URL(ctx.req.url).searchParams.get("query");
    return execute(query || "{ hello health }");
  },

  async POST(ctx) {
    try {
      const body = await ctx.req.json();
      return execute(body.query || "{ hello health }");
    } catch (error) {
      return json({ errors: [{ message: (error as Error).message }] }, 400);
    }
  },
});
`,

    // Islands - Counter component
    'islands/Counter.tsx': `import { useSignal } from "@preact/signals";

export default function Counter() {
  const count = useSignal(0);

  return (
    <div class="flex items-center gap-4">
      <button
        type="button"
        class="px-4 py-2 bg-blue-500 text-white rounded hover:bg-blue-600"
        onClick={() => count.value--}
      >
        -1
      </button>
      <span class="text-2xl font-bold">{count}</span>
      <button
        type="button"
        class="px-4 py-2 bg-blue-500 text-white rounded hover:bg-blue-600"
        onClick={() => count.value++}
      >
        +1
      </button>
    </div>
  );
}
`,

    // Routes - Home page
    'routes/index.tsx': `import Counter from "../islands/Counter.tsx";

export default function Home() {
  return (
    <main class="min-h-screen bg-gray-50">
      <div class="max-w-4xl mx-auto px-4 py-8">
        <h1 class="text-4xl font-bold text-gray-900 mb-4">
          Welcome to {{projectName}}
        </h1>
        <p class="text-lg text-gray-600 mb-8">
          A modern full-stack application built with Fresh and Deno
        </p>

        <div class="bg-white rounded-lg shadow-md p-6 mb-8">
          <h2 class="text-2xl font-semibold mb-4">Interactive Counter</h2>
          <p class="text-gray-600 mb-4">
            This is a Preact island with client-side interactivity
          </p>
          <Counter />
        </div>

        <div class="grid md:grid-cols-2 gap-6">
          <div class="bg-white rounded-lg shadow-md p-6">
            <h3 class="text-xl font-semibold mb-2">🚀 Fresh Framework</h3>
            <p class="text-gray-600">
              Modern full-stack framework with SSR and islands architecture
            </p>
          </div>

          <div class="bg-white rounded-lg shadow-md p-6">
            <h3 class="text-xl font-semibold mb-2">⚡ Deno Runtime</h3>
            <p class="text-gray-600">
              Secure, fast JavaScript/TypeScript runtime
            </p>
          </div>

          <div class="bg-white rounded-lg shadow-md p-6">
            <h3 class="text-xl font-semibold mb-2">🏝️ Islands Architecture</h3>
            <p class="text-gray-600">
              Progressive enhancement with zero JS by default
            </p>
          </div>

          <div class="bg-white rounded-lg shadow-md p-6">
            <h3 class="text-xl font-semibold mb-2">🎨 Tailwind CSS</h3>
            <p class="text-gray-600">
              Utility-first CSS framework for rapid UI development
            </p>
          </div>
        </div>

        <div class="mt-8 bg-blue-50 rounded-lg p-6">
          <h3 class="text-xl font-semibold mb-2">📚 API Endpoints</h3>
          <ul class="list-disc list-inside text-gray-700 space-y-1">
            <li>GET /api/health - Health check</li>
            <li>POST /api/auth/register - Register user</li>
            <li>POST /api/auth/login - Login user</li>
            <li>GET /api/products - List products</li>
            <li>GET /api/users/me - Get current user (auth required)</li>
          </ul>
        </div>
      </div>
    </main>
  );
}
`,

    // Environment file
    '.env.example': `# Server
PORT=8000
DENO_ENVIRONMENT=development

# JWT
JWT_SECRET=change-this-secret-in-production
JWT_EXPIRATION=7d

# Database
DB_PATH=./data/db.json
`,

    // Dockerfile - Multi-stage optimized build
    'Dockerfile': `# =============================================================================
# Fresh 2 production image: build the bundle, then serve it with \`deno serve\`
# =============================================================================
FROM denoland/deno:2.9.6

WORKDIR /app

COPY . .

# Install npm dependencies and build the production bundle into ./_fresh
RUN deno install && deno task build && deno cache _fresh/server.js

# Run as the non-root user shipped with the image
RUN chown -R deno:deno /app
USER deno

ENV PORT=8000
EXPOSE 8000

# Health check
HEALTHCHECK --interval=30s --timeout=10s --start-period=10s --retries=3 \\
    CMD deno eval "const r = await fetch('http://localhost:' + (Deno.env.get('PORT') ?? '8000') + '/api/health'); Deno.exit(r.ok ? 0 : 1)" || exit 1

CMD deno serve -A --port \${PORT} _fresh/server.js
`,

    // Docker Compose
    'docker-compose.yml': `version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - JWT_SECRET=change-this-secret
      - DENO_ENVIRONMENT=production
    restart: unless-stopped
`,

    // Tests
    'tests/main_test.ts': `import { assertEquals, assertExists } from "@std/assert";
import { db } from "../db.ts";
import { createToken, verifyToken } from "../utils/jwt.ts";

Deno.test("Database initialization", async () => {
  await db.initialize();

  const users = db.getUsers();
  assertExists(users);
  assertEquals(users.length > 0, true);
});

Deno.test("User authentication", async () => {
  await db.initialize();

  const user = await db.verifyUser("admin@example.com", "admin123");
  assertExists(user);
  assertEquals(user.email, "admin@example.com");
  assertEquals(user.role, "admin");
});

Deno.test("Product management", async () => {
  await db.initialize();

  const products = db.getProducts();
  assertExists(products);
  assertEquals(products.length > 0, true);
});

Deno.test("JWT round trip", async () => {
  const token = await createToken({ sub: "1", email: "admin@example.com", role: "admin" });
  const payload = await verifyToken(token);

  assertExists(payload);
  assertEquals(payload.sub, "1");
  assertEquals(payload.role, "admin");

  // A tampered token is rejected
  assertEquals(await verifyToken(token.slice(0, -2) + "xx"), null);
  assertEquals(await verifyToken("not-a-jwt"), null);
});
`,

    // README
    'README.md': `# {{projectName}}

A modern full-stack web application built with Fresh framework on Deno runtime with SSR and islands architecture.

## Features

- **Fresh Framework**: Modern full-stack framework with edge-first architecture
- **Deno Runtime**: Secure, fast JavaScript/TypeScript runtime
- **SSR + Islands**: Server-side rendering with progressive enhancement
- **Preact**: Fast 3kB React alternative
- **Tailwind CSS**: Utility-first CSS framework
- **JWT Authentication**: Token-based authentication
- **In-Memory Database**: Simple, fast data persistence
- **Docker Support**: Containerized deployment

## Requirements

- Deno 2.x (Fresh 2 is installed from JSR; no deno.land access is needed)

## Quick Start

1. Clone and navigate to the project:
   \`\`\`bash
   cd {{projectName}}
   \`\`\`

2. Start the development server (live reload):
   \`\`\`bash
   deno task dev
   \`\`\`

3. Visit http://localhost:8000

## Available Scripts

\`\`\`bash
deno task dev        # Start dev server with live reload
deno task build      # Build the production bundle into ./_fresh
deno task start      # Serve the production bundle (run build first)
deno task test       # Run the tests
deno task check      # Type-check every module
\`\`\`

## API Endpoints

### Health
- \`GET /api/health\` - Health check

### Authentication
- \`POST /api/auth/register\` - Register new user
- \`POST /api/auth/login\` - Login user

### Products
- \`GET /api/products\` - List all products
- \`GET /api/products/:id\` - Get product by ID
- \`POST /api/products\` - Create product (admin only)
- \`PUT /api/products/:id\` - Update product (admin only)
- \`DELETE /api/products/:id\` - Delete product (admin only)

### Users
- \`GET /api/users/me\` - Get current user (auth required)
- \`GET /api/users\` - List all users (admin only)

## Default Credentials

- Email: \`admin@example.com\`
- Password: \`admin123\`

## Project Structure

\`\`\`
├── islands/           # Client-side islands
├── routes/            # File-based routing
│   ├── _middleware.ts # Resolves the Bearer token into ctx.state.user
│   ├── api/          # API endpoints
│   ├── graphql.ts    # GraphQL endpoint
│   └── index.tsx     # Home page
├── middleware/        # Route guards (requireAuth, requireRole)
├── utils/             # JWT and response helpers
├── static/            # Static files and the Tailwind entry stylesheet
├── db.ts             # Database layer
├── config.ts         # Configuration
├── state.ts          # Type of ctx.state
├── dev.ts            # Dev server / build script
└── main.ts           # App entry point
\`\`\`

## What is Fresh?

Fresh is a modern web framework that provides:
- **Edge-first**: Deploy anywhere with Deno Deploy
- **Islands Architecture**: Zero JS by default, opt-in interactivity
- **Build Step Only For Production**: \`deno task build\` bundles islands and CSS
- **Type-Safe**: Full TypeScript support
- **Fast**: Sub-millisecond cold starts

## Islands Architecture

Fresh uses islands architecture where:
- Most of the page is server-rendered (no JS sent to client)
- Interactive parts are islands that hydrate independently
- Better performance and progressive enhancement

## Docker

Build and run with Docker:

\`\`\`bash
docker build -t {{projectName}} .
docker run -p 8000:8000 {{projectName}}
\`\`\`

Or use Docker Compose:

\`\`\`bash
docker-compose up
\`\`\`

## License

MIT
`,

    'dev.ts': `#!/usr/bin/env -S deno run -A --watch=static/,routes/
import { tailwind } from "@fresh/plugin-tailwind";
import { Builder } from "fresh/dev";

const builder = new Builder();
tailwind(builder);

if (Deno.args.includes("build")) {
  // deno task build: writes the production bundle to ./_fresh
  await builder.build();
} else {
  // deno task dev: serves ./main.ts with live reload
  await builder.listen(() => import("./main.ts"));
}
`,

    'state.ts': `import { createDefine } from "fresh";
import type { JWTPayload } from "./utils/jwt.ts";

// Shape of ctx.state, shared by middleware, layouts and routes.
export interface State {
  // The authenticated user, set by routes/_middleware.ts (null when anonymous)
  user: JWTPayload | null;
}

export const define = createDefine<State>();
`,

    'static/styles.css': `@import "tailwindcss";
`,

    'utils/http.ts': `// Small helper for JSON responses.
export function json(body: unknown, status = 200): Response {
  return new Response(JSON.stringify(body), {
    status,
    headers: { "Content-Type": "application/json" },
  });
}
`,

    'routes/_app.tsx': `import { define } from "../state.ts";

export default define.page(function App({ Component }) {
  return (
    <html>
      <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>{{projectName}}</title>
        <link rel="stylesheet" href="/styles.css" />
      </head>
      <body>
        <Component />
      </body>
    </html>
  );
});
`,

    'routes/_middleware.ts': `import { define } from "../state.ts";
import { verifyToken } from "../utils/jwt.ts";

// Runs for every request: resolves "Authorization: Bearer <jwt>" into ctx.state.user.
export const handler = define.middleware(async (ctx) => {
  const authHeader = ctx.req.headers.get("Authorization");
  ctx.state.user = authHeader?.startsWith("Bearer ")
    ? await verifyToken(authHeader.substring(7))
    : null;

  return ctx.next();
});
`,

    'routes/api/users/index.ts': `import { define } from "../../../state.ts";
import { db } from "../../../db.ts";
import { requireRole } from "../../../middleware/auth.ts";
import { json } from "../../../utils/http.ts";

// GET /api/users: list all users (admin only)
export const handler = define.handlers({
  GET(ctx) {
    const denied = requireRole(ctx, "admin");
    if (denied) return denied;

    const users = db.getUsers();
    return json({ users, count: users.length });
  },
});
`,

    'routes/api/users/me.ts': `import { define } from "../../../state.ts";
import { db } from "../../../db.ts";
import { requireAuth } from "../../../middleware/auth.ts";
import { json } from "../../../utils/http.ts";

// GET /api/users/me: the authenticated user
export const handler = define.handlers({
  GET(ctx) {
    const denied = requireAuth(ctx);
    if (denied) return denied;

    const user = db.getUserById(ctx.state.user!.sub);
    if (!user) {
      return json({ error: "User not found" }, 404);
    }
    return json({ user });
  },
});
`,

    'routes/api/auth/[action].ts': `import { define } from "../../../state.ts";
import { db } from "../../../db.ts";
import { createToken } from "../../../utils/jwt.ts";
import { json } from "../../../utils/http.ts";

// POST /api/auth/login and POST /api/auth/register
export const handler = define.handlers({
  async POST(ctx) {
    const action = ctx.params.action;

    if (action !== "login" && action !== "register") {
      return json({ error: "Not Found" }, 404);
    }

    let body: Record<string, string>;
    try {
      body = await ctx.req.json();
    } catch {
      return json({ error: "Invalid request" }, 400);
    }

    return action === "login" ? await handleLogin(body) : await handleRegister(body);
  },
});

async function handleLogin(body: Record<string, string>): Promise<Response> {
  const { email, password } = body;

  if (!email || !password) {
    return json({ error: "Email and password required" }, 400);
  }

  const user = await db.verifyUser(email, password);
  if (!user) {
    return json({ error: "Invalid credentials" }, 401);
  }

  const token = await createToken({ sub: user.id, email: user.email, role: user.role });

  return json({
    token,
    user: { id: user.id, email: user.email, name: user.name, role: user.role },
  });
}

async function handleRegister(body: Record<string, string>): Promise<Response> {
  const { email, password, name } = body;

  if (!email || !password || !name) {
    return json({ error: "Email, password, and name required" }, 400);
  }

  if (password.length < 6) {
    return json({ error: "Password must be at least 6 characters" }, 400);
  }

  if (db.getUserByEmail(email)) {
    return json({ error: "Email already registered" }, 409);
  }

  const user = await db.createUser({ email, password, name, role: "user" });
  const token = await createToken({ sub: user.id, email: user.email, role: user.role });

  return json(
    {
      token,
      user: { id: user.id, email: user.email, name: user.name, role: user.role },
    },
    201,
  );
}
`,

    'routes/api/products/[id].ts': `import { define } from "../../../state.ts";
import { db } from "../../../db.ts";
import { requireRole } from "../../../middleware/auth.ts";
import { json } from "../../../utils/http.ts";

export const handler = define.handlers({
  // GET /api/products/:id
  GET(ctx) {
    const product = db.getProductById(ctx.params.id);
    if (!product) {
      return json({ error: "Product not found" }, 404);
    }
    return json({ product });
  },

  // PUT /api/products/:id (admin only)
  async PUT(ctx) {
    const denied = requireRole(ctx, "admin");
    if (denied) return denied;

    let body: Record<string, unknown>;
    try {
      body = await ctx.req.json();
    } catch {
      return json({ error: "Invalid request" }, 400);
    }

    const product = db.updateProduct(ctx.params.id, {
      ...(typeof body.name === "string" && { name: body.name }),
      ...(typeof body.description === "string" && { description: body.description }),
      ...(body.price !== undefined && { price: Number(body.price) }),
      ...(body.stock !== undefined && { stock: Number(body.stock) }),
    });
    if (!product) {
      return json({ error: "Product not found" }, 404);
    }
    return json({ product });
  },

  // DELETE /api/products/:id (admin only)
  DELETE(ctx) {
    const denied = requireRole(ctx, "admin");
    if (denied) return denied;

    if (!db.deleteProduct(ctx.params.id)) {
      return json({ error: "Product not found" }, 404);
    }
    return new Response(null, { status: 204 });
  },
});
`,

    'routes/api/products/index.ts': `import { define } from "../../../state.ts";
import { db } from "../../../db.ts";
import { requireRole } from "../../../middleware/auth.ts";
import { json } from "../../../utils/http.ts";

export const handler = define.handlers({
  // GET /api/products: list all products
  GET() {
    const products = db.getProducts();
    return json({ products, count: products.length });
  },

  // POST /api/products: create a product (admin only)
  async POST(ctx) {
    const denied = requireRole(ctx, "admin");
    if (denied) return denied;

    let body: Record<string, unknown>;
    try {
      body = await ctx.req.json();
    } catch {
      return json({ error: "Invalid request" }, 400);
    }

    const { name, description, price, stock } = body;
    if (typeof name !== "string" || !name || Number.isNaN(Number(price))) {
      return json({ error: "Name and a numeric price are required" }, 400);
    }

    const product = db.createProduct({
      name,
      description: typeof description === "string" ? description : undefined,
      price: Number(price),
      stock: Number(stock) || 0,
    });

    return json({ product }, 201);
  },
});
`
  }
};
