import type { AgentsDocFile } from '@re-shell/contracts';

/**
 * Pure, deterministic generator for "agent-readiness" documentation.
 *
 * Given a description of the workspace surface — discovered packages (name,
 * path, scripts, internal dependencies), the command catalogue surface, and a
 * small amount of project metadata — this module produces the exact bytes for:
 *
 *   - the ROOT `AGENTS.md` (project overview, structure, build/test/lint, the
 *     package boundary map, the JSON-contract location, and do-not-touch zones),
 *   - one PER-PACKAGE `AGENTS.md` (that package's commands, boundaries, deps),
 *   - an `llms.txt`-style machine index (a concise text index of the surface).
 *
 * There is NO I/O here: every function takes plain data and returns strings.
 * The command layer (agents.group.ts) is the only place that touches the
 * filesystem — it discovers the workspace, calls this generator, then writes or
 * compares the returned content. Keeping generation pure makes it trivially
 * testable and makes the drift check a byte-for-byte equality of pure outputs.
 */

/** The well-known repo-relative paths this generator emits to. */
export const ROOT_AGENTS_FILE = 'AGENTS.md';
export const LLMS_INDEX_FILE = 'llms.txt';
export const PACKAGE_AGENTS_FILE = 'AGENTS.md';

/** Marker line that identifies a file as generated by this tool. */
const GENERATED_MARKER =
  '<!-- generated by `re-shell agents` — edit via the generator, then `re-shell agents sync` -->';

/**
 * A single workspace package as discovered on disk. `dir` is the repo-relative
 * directory (POSIX separators, e.g. "packages/cli"); `relScripts` is the subset
 * of npm scripts we surface (build/test/lint and friends). `internalDeps` are
 * the names of OTHER workspace packages this one depends on (already resolved by
 * the caller against the package set), used to draw boundary edges.
 */
export interface AgentsPackageInput {
  name: string;
  dir: string;
  description?: string;
  scripts: Record<string, string>;
  internalDeps: string[];
}

/**
 * The full, pre-discovered workspace surface handed to the generator. Everything
 * here is plain data so the generator stays pure and order-stable.
 */
export interface AgentsWorkspaceInput {
  /** Project / monorepo name (root package.json `name`). */
  projectName: string;
  /** Optional one-line project description (root package.json `description`). */
  projectDescription?: string;
  /** Detected package manager command (e.g. "pnpm"). */
  packageManager: string;
  /** Root-level scripts (build/test/lint) used for the top-level commands. */
  rootScripts: Record<string, string>;
  /** Discovered workspace packages, in caller-provided order. */
  packages: AgentsPackageInput[];
  /**
   * Repo-relative path to the JSON-contract source of truth (the contracts
   * package entry), surfaced so agents know where wire shapes are defined.
   */
  contractsPath?: string;
  /** Top-level command groups the CLI exposes (from the command catalogue). */
  commandGroups: string[];
  /**
   * Repo-relative globs/dirs agents must NOT edit (build output, generated
   * code). Sorted + de-duped here for deterministic output.
   */
  doNotTouch: string[];
}

/** Script keys we surface, in priority order, with friendly labels. */
const SURFACED_SCRIPTS: ReadonlyArray<readonly [string, string]> = [
  ['build', 'Build'],
  ['test', 'Test'],
  ['lint', 'Lint'],
  ['typecheck', 'Type-check'],
  ['dev', 'Dev'],
];

/** Stable string sort that never mutates its input. */
function sortedUnique(values: readonly string[]): string[] {
  return Array.from(new Set(values)).sort((a, b) => a.localeCompare(b));
}

/**
 * Render the workspace-wide command block from a script map. We always render
 * via the detected package manager so the commands are copy-pasteable. Only
 * scripts that actually exist are emitted (no fabricated commands).
 */
function renderRootCommands(pm: string, scripts: Record<string, string>): string[] {
  const lines: string[] = [];
  for (const [key, label] of SURFACED_SCRIPTS) {
    if (typeof scripts[key] === 'string') {
      lines.push(`- ${label}: \`${pm} run ${key}\``);
    }
  }
  return lines;
}

/**
 * Render the per-package command block. Commands are scoped to the package via
 * the package manager's `--filter`, mirroring how the repo is actually driven.
 */
function renderPackageCommands(
  pm: string,
  pkg: AgentsPackageInput
): string[] {
  const lines: string[] = [];
  for (const [key, label] of SURFACED_SCRIPTS) {
    if (typeof pkg.scripts[key] === 'string') {
      lines.push(`- ${label}: \`${pm} --filter ${pkg.name} run ${key}\``);
    }
  }
  return lines;
}

/**
 * Build the ROOT AGENTS.md content. Deterministic for a given input: identical
 * input bytes in, identical bytes out (this is what makes `agents check` a
 * stable CI gate).
 */
export function generateRootAgents(ws: AgentsWorkspaceInput): string {
  const lines: string[] = [];
  lines.push(`# AGENTS.md`);
  lines.push('');
  lines.push(GENERATED_MARKER);
  lines.push('');
  lines.push(`> Agent-readiness guide for **${ws.projectName}**.`);
  if (ws.projectDescription) {
    lines.push(`>`);
    lines.push(`> ${ws.projectDescription}`);
  }
  lines.push('');

  lines.push(`## Project overview`);
  lines.push('');
  lines.push(
    `This is a ${ws.packageManager} workspace with ${ws.packages.length} package(s). ` +
      `Work inside the package that owns the surface you are changing; respect the ` +
      `package boundaries below and keep changes scoped.`
  );
  lines.push('');

  lines.push(`## Commands`);
  lines.push('');
  const rootCmds = renderRootCommands(ws.packageManager, ws.rootScripts);
  if (rootCmds.length > 0) {
    lines.push(`Run from the repo root:`);
    lines.push('');
    lines.push(...rootCmds);
  } else {
    lines.push(`No root-level build/test/lint scripts were detected.`);
  }
  lines.push('');

  lines.push(`## Structure`);
  lines.push('');
  lines.push(`| Package | Path | Depends on |`);
  lines.push(`| --- | --- | --- |`);
  for (const pkg of ws.packages) {
    const deps = sortedUnique(pkg.internalDeps);
    lines.push(
      `| \`${pkg.name}\` | \`${pkg.dir}\` | ${deps.length ? deps.map(d => `\`${d}\``).join(', ') : '—'} |`
    );
  }
  lines.push('');

  lines.push(`## Package boundaries`);
  lines.push('');
  lines.push(
    `Each package owns its own directory. Do not reach across package roots to ` +
      `mutate another package's internals — depend on its published entry point ` +
      `instead. Internal dependency edges:`
  );
  lines.push('');
  for (const pkg of ws.packages) {
    const deps = sortedUnique(pkg.internalDeps);
    lines.push(`- \`${pkg.name}\` → ${deps.length ? deps.map(d => `\`${d}\``).join(', ') : 'no internal deps'}`);
  }
  lines.push('');

  if (ws.contractsPath) {
    lines.push(`## JSON contract`);
    lines.push('');
    lines.push(
      `Cross-process / \`--json\` wire shapes are defined as the single source of ` +
        `truth in \`${ws.contractsPath}\`. Add or change wire shapes THERE (zod + ` +
        `inferred types), never by hand-writing duplicate types in consumers.`
    );
    lines.push('');
  }

  if (ws.commandGroups.length > 0) {
    lines.push(`## CLI command groups`);
    lines.push('');
    lines.push(
      sortedUnique(ws.commandGroups)
        .map(g => `\`${g}\``)
        .join(', ')
    );
    lines.push('');
  }

  lines.push(`## Do not touch`);
  lines.push('');
  lines.push(`These paths are build output or generated; never edit them by hand:`);
  lines.push('');
  const dnt = sortedUnique(ws.doNotTouch);
  if (dnt.length > 0) {
    for (const p of dnt) {
      lines.push(`- \`${p}\``);
    }
  } else {
    lines.push(`- (none detected)`);
  }
  lines.push('');

  return lines.join('\n');
}

/**
 * Build a single PER-PACKAGE AGENTS.md. Deterministic for a given package
 * input. Surfaces the package's own commands, its place in the workspace, and
 * its internal dependency edges.
 */
export function generatePackageAgents(
  ws: AgentsWorkspaceInput,
  pkg: AgentsPackageInput
): string {
  const lines: string[] = [];
  lines.push(`# AGENTS.md — ${pkg.name}`);
  lines.push('');
  lines.push(GENERATED_MARKER);
  lines.push('');
  if (pkg.description) {
    lines.push(`> ${pkg.description}`);
    lines.push('');
  }
  lines.push(
    `Package directory: \`${pkg.dir}\`. Part of the **${ws.projectName}** ` +
      `${ws.packageManager} workspace. Keep changes scoped to this directory.`
  );
  lines.push('');

  lines.push(`## Commands`);
  lines.push('');
  const cmds = renderPackageCommands(ws.packageManager, pkg);
  if (cmds.length > 0) {
    lines.push(...cmds);
  } else {
    lines.push(`No build/test/lint scripts were detected for this package.`);
  }
  lines.push('');

  lines.push(`## Boundaries`);
  lines.push('');
  const deps = sortedUnique(pkg.internalDeps);
  if (deps.length > 0) {
    lines.push(`Internal workspace dependencies:`);
    lines.push('');
    for (const d of deps) {
      lines.push(`- \`${d}\``);
    }
    lines.push('');
    lines.push(
      `Depend on these via their entry points only; do not import from their ` +
        `internal source paths.`
    );
  } else {
    lines.push(`This package has no internal workspace dependencies.`);
  }
  lines.push('');

  return lines.join('\n');
}

/**
 * Build the `llms.txt`-style machine index: a concise, line-oriented index of
 * the workspace surface (project, commands, packages, contract location). It is
 * intentionally terse and stable so an agent can load it cheaply.
 */
export function generateLlmsIndex(ws: AgentsWorkspaceInput): string {
  const lines: string[] = [];
  lines.push(`# ${ws.projectName}`);
  if (ws.projectDescription) {
    lines.push(`> ${ws.projectDescription}`);
  }
  lines.push('');
  lines.push(`## Commands`);
  for (const line of renderRootCommands(ws.packageManager, ws.rootScripts)) {
    // Strip the "Label: " prefix to keep the index terse; keep the code span.
    lines.push(line);
  }
  lines.push('');
  lines.push(`## Packages`);
  for (const pkg of ws.packages) {
    const deps = sortedUnique(pkg.internalDeps);
    lines.push(
      `- ${pkg.name} (${pkg.dir})${deps.length ? ` -> ${deps.join(', ')}` : ''}: ${pkg.dir}/${PACKAGE_AGENTS_FILE}`
    );
  }
  lines.push('');
  if (ws.contractsPath) {
    lines.push(`## Contract`);
    lines.push(`- JSON wire shapes: ${ws.contractsPath}`);
    lines.push('');
  }
  if (ws.commandGroups.length > 0) {
    lines.push(`## CLI groups`);
    lines.push(`- ${sortedUnique(ws.commandGroups).join(', ')}`);
    lines.push('');
  }
  return lines.join('\n');
}

/**
 * A single generated artifact: its repo-relative path, role, and exact content.
 * The command layer writes / compares `content`; `bytes` is derived for the
 * --json summary.
 */
export interface GeneratedAgentsFile {
  path: string;
  kind: AgentsDocFile['kind'];
  content: string;
}

/** UTF-8 byte length of a string (matches what is written to disk). */
export function byteLength(content: string): number {
  return Buffer.byteLength(content, 'utf8');
}

/** Join a package dir and the package AGENTS.md filename using POSIX separators. */
function packageDocPath(dir: string): string {
  const clean = dir.replace(/\/+$/, '');
  return clean.length > 0 ? `${clean}/${PACKAGE_AGENTS_FILE}` : PACKAGE_AGENTS_FILE;
}

/**
 * Generate the FULL set of agent-doc artifacts for a workspace: the root
 * AGENTS.md, one per-package AGENTS.md, and the llms.txt index. The returned
 * array is the complete, ordered set the command layer should write/compare —
 * order is deterministic (root, then packages in input order, then index).
 */
export function generateAllAgentsDocs(ws: AgentsWorkspaceInput): GeneratedAgentsFile[] {
  const files: GeneratedAgentsFile[] = [];

  files.push({
    path: ROOT_AGENTS_FILE,
    kind: 'root',
    content: generateRootAgents(ws),
  });

  for (const pkg of ws.packages) {
    files.push({
      path: packageDocPath(pkg.dir),
      kind: 'package',
      content: generatePackageAgents(ws, pkg),
    });
  }

  files.push({
    path: LLMS_INDEX_FILE,
    kind: 'index',
    content: generateLlmsIndex(ws),
  });

  return files;
}

/** Convert a generated file to its contract `AgentsDocFile` summary. */
export function toAgentsDocFile(file: GeneratedAgentsFile): AgentsDocFile {
  return { path: file.path, kind: file.kind, bytes: byteLength(file.content) };
}
