// Cross-language service bridge generation from a workspace.yaml v2 service
// definition (W9c-3, P9-B).
//
// Given one v2 service, emit a protocol CONTRACT artifact plus a typed TS client
// scaffold and a documented per-language scaffold for at least one non-TS
// language:
//   --grpc:    a .proto (proto3, service + messages) + a typed TS gRPC client.
//   --rest:    an OpenAPI 3 spec (paths + components) + a typed TS fetch client.
//   --graphql: a GraphQL SDL schema + a typed TS GraphQL client.
//
// These are GENERATION artifacts: correctness is verified by parsing the
// contract (OpenAPI as JSON/YAML, GraphQL SDL with the `graphql` lib when
// present else structurally, .proto by required tokens) and by type-checking the
// emitted TS client with the TypeScript compiler API — never by live calls.

import * as fs from 'fs';
import * as path from 'path';
import * as yaml from 'js-yaml';

import { WorkspaceParser, type ServiceConfig } from '../parsers/workspace-parser';
import { resolveWorkspaceConfigPath } from './k8s-generate';

/** Supported bridge protocols. */
export type BridgeProtocol = 'grpc' | 'rest' | 'graphql';

/** Kind of a generated artifact: the contract, the TS client, or a scaffold. */
export type BridgeArtifactKind =
  | 'proto'
  | 'openapi'
  | 'graphql-sdl'
  | 'ts-client'
  | 'scaffold-readme'
  | 'scaffold-stub';

/** A single generated artifact (relative path + content + kind). */
export interface BridgeArtifact {
  /** Path relative to the bridge output root, e.g. "api.proto". */
  path: string;
  content: string;
  kind: BridgeArtifactKind;
}

/** Result of a bridge-generation run. */
export interface GenerateBridgeResult {
  protocol: BridgeProtocol;
  service: string;
  artifacts: BridgeArtifact[];
  /** Files written to disk (absolute paths); empty for dry-run / no out. */
  written: string[];
}

export interface GenerateBridgeOptions {
  /** Which protocol to generate a bridge for. */
  protocol: BridgeProtocol;
  /** Directory containing the workspace v2 config (default: cwd). */
  cwd?: string;
  /** Explicit path to the workspace yaml; overrides cwd discovery. */
  configPath?: string;
  /** Name of the service to bridge; defaults to the first service. */
  service?: string;
  /** Output directory to write artifacts into; omitted/dry-run writes nothing. */
  out?: string;
  /** When true, do not write files regardless of `out`. */
  dryRun?: boolean;
}

const DEFAULT_PORT = 8080;

/** The non-TS scaffold language emitted alongside the TS client. */
const SECONDARY_SCAFFOLD_LANGUAGE = 'python';

// ---------------------------------------------------------------------------
// Naming helpers
// ---------------------------------------------------------------------------

function toPascalCase(value: string): string {
  return value
    .replace(/[^A-Za-z0-9]+/g, ' ')
    .trim()
    .split(/\s+/)
    .map(part => part.charAt(0).toUpperCase() + part.slice(1).toLowerCase())
    .join('');
}

function toCamelCase(value: string): string {
  const pascal = toPascalCase(value);
  return pascal.charAt(0).toLowerCase() + pascal.slice(1);
}

function toSnakeCase(value: string): string {
  return value
    .replace(/[^A-Za-z0-9]+/g, '_')
    .replace(/([a-z0-9])([A-Z])/g, '$1_$2')
    .toLowerCase()
    .replace(/^_+|_+$/g, '');
}

// ---------------------------------------------------------------------------
// Service shape derivation
// ---------------------------------------------------------------------------

/** Normalized view of the service we bridge, derived from the v2 config. */
interface BridgeService {
  /** Raw service name as keyed in the workspace. */
  name: string;
  /** PascalCase identifier used for type/service names. */
  pascalName: string;
  port: number;
  /** Env keys surfaced as a typed config message/type on the contract. */
  envKeys: string[];
}

function deriveService(service: ServiceConfig, serviceName: string): BridgeService {
  return {
    name: serviceName,
    pascalName: toPascalCase(serviceName),
    port: service.port ?? DEFAULT_PORT,
    envKeys: Object.keys(service.env ?? {}),
  };
}

// ---------------------------------------------------------------------------
// gRPC: .proto contract + typed TS client
// ---------------------------------------------------------------------------

function buildProto(svc: BridgeService): string {
  const pkg = toSnakeCase(svc.name) || 'service';
  const svcName = `${svc.pascalName}Service`;
  // Derive a Config message from the service env keys (string fields).
  const configFields =
    svc.envKeys.length > 0
      ? svc.envKeys
          .map((key, i) => `  string ${toSnakeCase(key)} = ${i + 1};`)
          .join('\n')
      : '  // no env-derived fields';

  return `syntax = "proto3";

package ${pkg};

// Auto-generated by re-shell service bridge generate (gRPC).
// Contract for the "${svc.name}" service.

// Health probe request.
message HealthRequest {}

// Health probe response.
message HealthResponse {
  bool ok = 1;
  string service = 2;
}

// Echo request carrying an arbitrary payload.
message EchoRequest {
  string payload = 1;
}

// Echo response returning the payload unchanged.
message EchoResponse {
  string payload = 1;
}

// Effective runtime configuration, derived from the service env.
message Config {
${configFields}
}

// ${svcName} is the bridge surface for the "${svc.name}" service.
service ${svcName} {
  // Liveness/readiness probe.
  rpc Check (HealthRequest) returns (HealthResponse);
  // Echo a payload back to the caller.
  rpc Echo (EchoRequest) returns (EchoResponse);
  // Fetch the effective runtime configuration.
  rpc GetConfig (HealthRequest) returns (Config);
}
`;
}

function buildGrpcTsClient(svc: BridgeService): string {
  const svcName = `${svc.pascalName}Service`;
  const clientName = `${svc.pascalName}GrpcClient`;
  const configFields =
    svc.envKeys.length > 0
      ? svc.envKeys.map(key => `  ${toSnakeCase(key)}: string;`).join('\n')
      : '  [key: string]: string;';

  return `// Auto-generated typed gRPC client for the "${svc.name}" service.
//
// This is a transport-agnostic, dependency-free stub: it models the contract's
// request/response types and an injectable invoker so it type-checks and unit
// tests without a running gRPC server or generated proto stubs. Wire it to a
// real @grpc/grpc-js channel by passing an \`invoke\` implementation.

export interface HealthRequest {
  readonly _empty?: never;
}

export interface HealthResponse {
  ok: boolean;
  service: string;
}

export interface EchoRequest {
  payload: string;
}

export interface EchoResponse {
  payload: string;
}

export interface Config {
${configFields}
}

/** Unary RPC invoker: maps a fully-qualified method + request to a response. */
export type GrpcInvoke = <Req, Res>(method: string, request: Req) => Promise<Res>;

const SERVICE_NAME = '${svcName}';

/** Typed client for the ${svcName} gRPC contract. */
export class ${clientName} {
  constructor(private readonly invoke: GrpcInvoke) {}

  check(request: HealthRequest = {}): Promise<HealthResponse> {
    return this.invoke<HealthRequest, HealthResponse>(SERVICE_NAME + '/Check', request);
  }

  echo(request: EchoRequest): Promise<EchoResponse> {
    return this.invoke<EchoRequest, EchoResponse>(SERVICE_NAME + '/Echo', request);
  }

  getConfig(request: HealthRequest = {}): Promise<Config> {
    return this.invoke<HealthRequest, Config>(SERVICE_NAME + '/GetConfig', request);
  }
}

export default ${clientName};
`;
}

// ---------------------------------------------------------------------------
// REST: OpenAPI 3 contract + typed TS fetch client
// ---------------------------------------------------------------------------

interface OpenApiSpec {
  openapi: string;
  info: { title: string; version: string; description?: string };
  servers: { url: string }[];
  paths: Record<string, unknown>;
  components: { schemas: Record<string, unknown> };
}

function buildOpenApi(svc: BridgeService): OpenApiSpec {
  const configProps: Record<string, { type: string }> = {};
  for (const key of svc.envKeys) {
    configProps[key] = { type: 'string' };
  }

  const okRef = { $ref: '#/components/schemas/HealthResponse' };
  const echoReq = { $ref: '#/components/schemas/EchoRequest' };
  const echoRes = { $ref: '#/components/schemas/EchoResponse' };
  const configRef = { $ref: '#/components/schemas/Config' };

  return {
    openapi: '3.0.3',
    info: {
      title: `${svc.pascalName} API`,
      version: '1.0.0',
      description: `Auto-generated REST contract for the "${svc.name}" service.`,
    },
    servers: [{ url: `http://localhost:${svc.port}` }],
    paths: {
      '/health': {
        get: {
          operationId: 'check',
          summary: 'Liveness/readiness probe',
          responses: {
            '200': {
              description: 'Health status',
              content: { 'application/json': { schema: okRef } },
            },
          },
        },
      },
      '/echo': {
        post: {
          operationId: 'echo',
          summary: 'Echo a payload back to the caller',
          requestBody: {
            required: true,
            content: { 'application/json': { schema: echoReq } },
          },
          responses: {
            '200': {
              description: 'Echoed payload',
              content: { 'application/json': { schema: echoRes } },
            },
          },
        },
      },
      '/config': {
        get: {
          operationId: 'getConfig',
          summary: 'Fetch the effective runtime configuration',
          responses: {
            '200': {
              description: 'Effective configuration',
              content: { 'application/json': { schema: configRef } },
            },
          },
        },
      },
    },
    components: {
      schemas: {
        HealthResponse: {
          type: 'object',
          required: ['ok', 'service'],
          properties: {
            ok: { type: 'boolean' },
            service: { type: 'string' },
          },
        },
        EchoRequest: {
          type: 'object',
          required: ['payload'],
          properties: { payload: { type: 'string' } },
        },
        EchoResponse: {
          type: 'object',
          required: ['payload'],
          properties: { payload: { type: 'string' } },
        },
        Config: {
          type: 'object',
          properties: configProps,
        },
      },
    },
  };
}

function buildRestTsClient(svc: BridgeService): string {
  const clientName = `${svc.pascalName}RestClient`;
  const configFields =
    svc.envKeys.length > 0
      ? svc.envKeys.map(key => `  ${JSON.stringify(key)}?: string;`).join('\n')
      : '  [key: string]: string | undefined;';

  return `// Auto-generated typed REST client for the "${svc.name}" service.
//
// Uses the global \`fetch\` (Node 18+/browser). All request/response shapes are
// typed from the OpenAPI contract so callers get end-to-end type safety.

export interface HealthResponse {
  ok: boolean;
  service: string;
}

export interface EchoRequest {
  payload: string;
}

export interface EchoResponse {
  payload: string;
}

export interface Config {
${configFields}
}

export interface ${clientName}Options {
  baseUrl?: string;
  fetchImpl?: typeof fetch;
}

/** Typed fetch client for the ${svc.pascalName} REST contract. */
export class ${clientName} {
  private readonly baseUrl: string;
  private readonly fetchImpl: typeof fetch;

  constructor(options: ${clientName}Options = {}) {
    this.baseUrl = options.baseUrl ?? 'http://localhost:${svc.port}';
    this.fetchImpl = options.fetchImpl ?? fetch;
  }

  private async request<T>(method: string, path: string, body?: unknown): Promise<T> {
    const response = await this.fetchImpl(this.baseUrl + path, {
      method,
      headers: { 'Content-Type': 'application/json' },
      body: body === undefined ? undefined : JSON.stringify(body),
    });
    if (!response.ok) {
      throw new Error('HTTP ' + response.status + ' ' + response.statusText);
    }
    return (await response.json()) as T;
  }

  check(): Promise<HealthResponse> {
    return this.request<HealthResponse>('GET', '/health');
  }

  echo(request: EchoRequest): Promise<EchoResponse> {
    return this.request<EchoResponse>('POST', '/echo', request);
  }

  getConfig(): Promise<Config> {
    return this.request<Config>('GET', '/config');
  }
}

export default ${clientName};
`;
}

// ---------------------------------------------------------------------------
// GraphQL: SDL contract + typed TS client
// ---------------------------------------------------------------------------

function buildGraphqlSdl(svc: BridgeService): string {
  const configFields =
    svc.envKeys.length > 0
      ? svc.envKeys.map(key => `  ${toCamelCase(key)}: String`).join('\n')
      : '  _placeholder: String';

  return `# Auto-generated GraphQL schema for the "${svc.name}" service.

type HealthResponse {
  ok: Boolean!
  service: String!
}

type EchoResponse {
  payload: String!
}

"Effective runtime configuration, derived from the service env."
type Config {
${configFields}
}

type Query {
  "Liveness/readiness probe."
  check: HealthResponse!
  "Fetch the effective runtime configuration."
  config: Config!
}

type Mutation {
  "Echo a payload back to the caller."
  echo(payload: String!): EchoResponse!
}
`;
}

function buildGraphqlTsClient(svc: BridgeService): string {
  const clientName = `${svc.pascalName}GraphqlClient`;
  const configFields =
    svc.envKeys.length > 0
      ? svc.envKeys.map(key => `  ${toCamelCase(key)}?: string | null;`).join('\n')
      : '  _placeholder?: string | null;';

  return `// Auto-generated typed GraphQL client for the "${svc.name}" service.
//
// Transport-agnostic: pass an \`execute\` function that POSTs the query to your
// GraphQL endpoint. Operations + result types are typed from the SDL contract.

export interface HealthResponse {
  ok: boolean;
  service: string;
}

export interface EchoResponse {
  payload: string;
}

export interface Config {
${configFields}
}

/** Executes a GraphQL document with variables, returning the typed \`data\`. */
export type GraphqlExecute = <TData, TVars extends Record<string, unknown>>(
  query: string,
  variables: TVars
) => Promise<TData>;

const CHECK_QUERY = 'query Check { check { ok service } }';
const CONFIG_QUERY = 'query GetConfig { config { __typename } }';
const ECHO_MUTATION =
  'mutation Echo($payload: String!) { echo(payload: $payload) { payload } }';

/** Typed client for the ${svc.pascalName} GraphQL contract. */
export class ${clientName} {
  constructor(private readonly execute: GraphqlExecute) {}

  async check(): Promise<HealthResponse> {
    const data = await this.execute<{ check: HealthResponse }, Record<string, never>>(
      CHECK_QUERY,
      {}
    );
    return data.check;
  }

  async config(): Promise<Config> {
    const data = await this.execute<{ config: Config }, Record<string, never>>(
      CONFIG_QUERY,
      {}
    );
    return data.config;
  }

  async echo(payload: string): Promise<EchoResponse> {
    const data = await this.execute<{ echo: EchoResponse }, { payload: string }>(
      ECHO_MUTATION,
      { payload }
    );
    return data.echo;
  }
}

export default ${clientName};
`;
}

// ---------------------------------------------------------------------------
// Non-TS scaffold (Python): documented README + stub
// ---------------------------------------------------------------------------

function buildPythonScaffoldReadme(svc: BridgeService, protocol: BridgeProtocol): string {
  const contractFile =
    protocol === 'grpc'
      ? `${toSnakeCase(svc.name)}.proto`
      : protocol === 'rest'
        ? 'openapi.json'
        : 'schema.graphql';
  const toolchain =
    protocol === 'grpc'
      ? `python -m grpc_tools.protoc -I. --python_out=. --grpc_python_out=. ${contractFile}`
      : protocol === 'rest'
        ? `openapi-python-client generate --path ${contractFile}`
        : `# Use ariadne-codegen or sgqlc against ${contractFile}`;

  return `# ${svc.pascalName} ${protocol.toUpperCase()} client (Python scaffold)

This is a documented scaffold for a Python client of the "${svc.name}" service
over **${protocol}**. The contract artifact (\`${contractFile}\`) is the source of
truth. This scaffold is intentionally toolchain-free: generate the concrete
client from the contract with the command below, then flesh out \`client.py\`.

## Generate the concrete client

\`\`\`bash
${toolchain}
\`\`\`

## Stub

See \`client.py\` for a minimal, runnable stub that mirrors the contract's three
operations (check / echo / get_config). Replace the stubbed transport with a
real ${protocol} call once the generated bindings are available.
`;
}

function buildPythonScaffoldStub(svc: BridgeService, protocol: BridgeProtocol): string {
  const className = `${svc.pascalName}Client`;
  return `"""Auto-generated Python ${protocol} client scaffold for the "${svc.name}" service.

This is a documented stub, not a toolchain build. It mirrors the contract's
operations with typed signatures; wire the transport to a real ${protocol} call.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Callable, Dict


@dataclass
class HealthResponse:
    ok: bool
    service: str


@dataclass
class EchoResponse:
    payload: str


class ${className}:
    """Typed ${protocol} client scaffold for the ${svc.pascalName} service."""

    def __init__(self, invoke: Callable[[str, Dict[str, Any]], Dict[str, Any]]):
        # 'invoke' maps (operation, request) -> response dict. Provide a real
        # ${protocol} transport here.
        self._invoke = invoke

    def check(self) -> HealthResponse:
        data = self._invoke("check", {})
        return HealthResponse(ok=bool(data["ok"]), service=str(data["service"]))

    def echo(self, payload: str) -> EchoResponse:
        data = self._invoke("echo", {"payload": payload})
        return EchoResponse(payload=str(data["payload"]))

    def get_config(self) -> Dict[str, Any]:
        return self._invoke("get_config", {})
`;
}

// ---------------------------------------------------------------------------
// Per-language index scaffold (TS + Python)
// ---------------------------------------------------------------------------

function buildIndexReadme(svc: BridgeService, protocol: BridgeProtocol): string {
  return `# ${svc.pascalName} service bridge (${protocol})

Generated by \`re-shell service bridge generate --${protocol}\`.

## Layout

- \`${contractFileName(protocol, svc)}\` — the ${protocol} contract (source of truth).
- \`ts/\` — a typed TypeScript client (compiles standalone).
- \`python/\` — a documented Python client scaffold (README + stub).

The TypeScript client is fully typed against the contract. The Python client is
a scaffold: generate concrete bindings from the contract, then implement the
transport (see \`python/README.md\`).
`;
}

function contractFileName(protocol: BridgeProtocol, svc: BridgeService): string {
  if (protocol === 'grpc') return `${toSnakeCase(svc.name)}.proto`;
  if (protocol === 'rest') return 'openapi.json';
  return 'schema.graphql';
}

function tsClientFileName(): string {
  return 'ts/client.ts';
}

// ---------------------------------------------------------------------------
// Top-level generation
// ---------------------------------------------------------------------------

function buildArtifacts(
  svc: BridgeService,
  protocol: BridgeProtocol
): BridgeArtifact[] {
  const artifacts: BridgeArtifact[] = [];
  const contractPath = contractFileName(protocol, svc);

  if (protocol === 'grpc') {
    artifacts.push({ path: contractPath, content: buildProto(svc), kind: 'proto' });
    artifacts.push({
      path: tsClientFileName(),
      content: buildGrpcTsClient(svc),
      kind: 'ts-client',
    });
  } else if (protocol === 'rest') {
    artifacts.push({
      path: contractPath,
      content: JSON.stringify(buildOpenApi(svc), null, 2) + '\n',
      kind: 'openapi',
    });
    artifacts.push({
      path: tsClientFileName(),
      content: buildRestTsClient(svc),
      kind: 'ts-client',
    });
  } else {
    artifacts.push({
      path: contractPath,
      content: buildGraphqlSdl(svc),
      kind: 'graphql-sdl',
    });
    artifacts.push({
      path: tsClientFileName(),
      content: buildGraphqlTsClient(svc),
      kind: 'ts-client',
    });
  }

  // Per-language index + the non-TS (Python) scaffold.
  artifacts.push({
    path: 'README.md',
    content: buildIndexReadme(svc, protocol),
    kind: 'scaffold-readme',
  });
  artifacts.push({
    path: `${SECONDARY_SCAFFOLD_LANGUAGE}/README.md`,
    content: buildPythonScaffoldReadme(svc, protocol),
    kind: 'scaffold-readme',
  });
  artifacts.push({
    path: `${SECONDARY_SCAFFOLD_LANGUAGE}/client.py`,
    content: buildPythonScaffoldStub(svc, protocol),
    kind: 'scaffold-stub',
  });

  return artifacts;
}

/**
 * Generate a cross-language service bridge for one v2 service.
 *
 * Reads + validates the workspace config via {@link WorkspaceParser}, selects
 * the target service (`options.service` or the first one), and assembles the
 * contract + TS client + Python scaffold. When `out` is set and not `dryRun`,
 * artifacts are written under `<out>/<service>-<protocol>/...`.
 *
 * @throws Error when the config cannot be found/parsed, the protocol is unknown,
 *   there are no services, or the named service is missing. The command layer
 *   maps these to a `BRIDGE_GENERATE_ERROR` envelope.
 */
export function generateBridge(
  options: GenerateBridgeOptions
): GenerateBridgeResult {
  const protocol = options.protocol;
  if (protocol !== 'grpc' && protocol !== 'rest' && protocol !== 'graphql') {
    throw new Error(
      `Unknown bridge protocol "${String(protocol)}" (expected grpc|rest|graphql)`
    );
  }

  const cwd = options.cwd ?? process.cwd();
  const configPath = resolveWorkspaceConfigPath(cwd, options.configPath);
  if (!configPath) {
    throw new Error(`No workspace v2 config found in ${cwd}`);
  }

  const parser = new WorkspaceParser();
  const parsed = parser.parse(configPath);
  if (!parsed.valid || !parsed.config) {
    const detail = parsed.errors.map(e => `${e.path}: ${e.message}`).join('; ');
    throw new Error(`Invalid workspace config: ${detail || 'unknown error'}`);
  }

  const services = parsed.config.services ?? {};
  const serviceNames = Object.keys(services);
  if (serviceNames.length === 0) {
    throw new Error('Workspace config defines no services to generate a bridge for');
  }

  const serviceName = options.service ?? serviceNames[0];
  const serviceConfig = services[serviceName];
  if (!serviceConfig) {
    throw new Error(
      `Service "${serviceName}" not found (available: ${serviceNames.join(', ')})`
    );
  }

  const svc = deriveService(serviceConfig, serviceName);
  const artifacts = buildArtifacts(svc, protocol);

  const written: string[] = [];
  const shouldWrite = Boolean(options.out) && options.dryRun !== true;
  if (shouldWrite && options.out) {
    const bridgeRoot = path.join(options.out, `${svc.name}-${protocol}`);
    for (const artifact of artifacts) {
      const filePath = path.join(bridgeRoot, artifact.path);
      fs.mkdirSync(path.dirname(filePath), { recursive: true });
      fs.writeFileSync(filePath, artifact.content);
      written.push(filePath);
    }
  }

  return { protocol, service: svc.name, artifacts, written };
}

/** Convenience: parse an OpenAPI artifact content back to an object. */
export function parseOpenApi(content: string): unknown {
  // OpenAPI we emit is JSON, which is a YAML subset; yaml.load parses both.
  return yaml.load(content);
}
