// Static source templates for the generated ReShellWorkspace operator
// scaffold (P9-D4). The operator is a Go program built on controller-runtime
// that reconciles a ReShellWorkspace custom resource into per-service
// Deployments, Services and PodDisruptionBudgets.
//
// The Go sources are authored here as template literals. Go struct tags and raw
// strings need a backtick, which cannot appear inside a JS template literal, so
// the character `§` stands in for it and `goSource()` swaps it back. Nothing
// else in the Go sources uses `§`.
//
// Everything is in `package main` on purpose: the scaffold has no self-imports,
// so the module path in go.mod is the only thing that depends on the user's
// `--module` choice.

/** Swap the `§` stand-in back to a Go backtick. */
function goSource(src: string): string {
  return src.replace(/§/g, '`');
}

/** Pinned dependency versions of the scaffold (kept in sync with the CRD target, Kubernetes 1.31). */
export const OPERATOR_DEPENDENCIES = {
  go: '1.23.0',
  controllerRuntime: 'v0.19.4',
  k8s: 'v0.31.4',
} as const;

/** go.mod for the generated operator. */
export function goMod(modulePath: string): string {
  return `module ${modulePath}

go ${OPERATOR_DEPENDENCIES.go}

require (
	k8s.io/api ${OPERATOR_DEPENDENCIES.k8s}
	k8s.io/apimachinery ${OPERATOR_DEPENDENCIES.k8s}
	k8s.io/client-go ${OPERATOR_DEPENDENCIES.k8s}
	sigs.k8s.io/controller-runtime ${OPERATOR_DEPENDENCIES.controllerRuntime}
)
`;
}

/** constants.go: identity of the custom resource (the only generated Go). */
export function constantsGo(identity: {
  group: string;
  version: string;
  kind: string;
  plural: string;
}): string {
  return `// Code generated by re-shell. DO NOT EDIT.

package main

// Identity of the custom resource this operator reconciles.
const (
	Group   = "${identity.group}"
	Version = "${identity.version}"
	Kind    = "${identity.kind}"
	Plural  = "${identity.plural}"
)
`;
}

/** types.go: the subset of the workspace v2 document the operator understands. */
export const TYPES_GO = goSource(String.raw`package main

import (
	"k8s.io/apimachinery/pkg/util/intstr"
)

// WorkspaceSpec is the subset of a re-shell workspace v2 document that the
// operator reconciles. Unknown fields are ignored (the CRD schema, derived from
// workspace-v2.schema.json, validates the full document).
type WorkspaceSpec struct {
	Name        string                 §json:"name"§
	Version     string                 §json:"version"§
	Description string                 §json:"description,omitempty"§
	Services    map[string]ServiceSpec §json:"services"§
	// Workspace-wide Kubernetes defaults (raw so they can be deep-merged with
	// each service's overrides before decoding into KubernetesSpec).
	Kubernetes map[string]interface{} §json:"kubernetes,omitempty"§
	Deployment *DeploymentSpec        §json:"deployment,omitempty"§
}

// DeploymentSpec carries workspace-level deployment defaults.
type DeploymentSpec struct {
	Replicas *int32 §json:"replicas,omitempty"§
}

// ServiceSpec is one entry under spec.services.
type ServiceSpec struct {
	Name        string                 §json:"name"§
	Port        int32                  §json:"port,omitempty"§
	Env         map[string]string      §json:"env,omitempty"§
	Resources   *LegacyResources       §json:"resources,omitempty"§
	HealthCheck *HealthCheck           §json:"healthCheck,omitempty"§
	Scaling     *Scaling               §json:"scaling,omitempty"§
	Kubernetes  map[string]interface{} §json:"kubernetes,omitempty"§
}

// LegacyResources is the workspace-schema resources block (cpu/memory request+limit).
type LegacyResources struct {
	CPU    *Quantities §json:"cpu,omitempty"§
	Memory *Quantities §json:"memory,omitempty"§
}

// Quantities is a request/limit pair.
type Quantities struct {
	Request string §json:"request,omitempty"§
	Limit   string §json:"limit,omitempty"§
}

// HealthCheck is the workspace-schema healthCheck block.
type HealthCheck struct {
	Path     string §json:"path,omitempty"§
	Interval *int32 §json:"interval,omitempty"§
	Timeout  *int32 §json:"timeout,omitempty"§
	Retries  *int32 §json:"retries,omitempty"§
}

// Scaling is the workspace-schema scaling block (only min is used: it sets the replica count).
type Scaling struct {
	Min *int32 §json:"min,omitempty"§
	Max *int32 §json:"max,omitempty"§
}

// KubernetesSpec mirrors the kubernetesConfig definition of the workspace schema.
type KubernetesSpec struct {
	Image                         *ImageSpec    §json:"image,omitempty"§
	Replicas                      *int32        §json:"replicas,omitempty"§
	Resources                     *K8sResources §json:"resources,omitempty"§
	SecurityContext               *SecuritySpec §json:"securityContext,omitempty"§
	AutomountServiceAccountToken  *bool         §json:"automountServiceAccountToken,omitempty"§
	Probes                        *ProbesSpec   §json:"probes,omitempty"§
	Strategy                      *StrategySpec §json:"strategy,omitempty"§
	RevisionHistoryLimit          *int32        §json:"revisionHistoryLimit,omitempty"§
	ProgressDeadlineSeconds       *int32        §json:"progressDeadlineSeconds,omitempty"§
	MinReadySeconds               *int32        §json:"minReadySeconds,omitempty"§
	TerminationGracePeriodSeconds *int64        §json:"terminationGracePeriodSeconds,omitempty"§
	PDB                           *PDBSpec      §json:"pdb,omitempty"§
}

// ImageSpec selects the container image.
type ImageSpec struct {
	Registry   string §json:"registry,omitempty"§
	Repository string §json:"repository,omitempty"§
	Tag        string §json:"tag,omitempty"§
	PullPolicy string §json:"pullPolicy,omitempty"§
}

// K8sResources is a Kubernetes-shaped resources block.
type K8sResources struct {
	Requests map[string]string §json:"requests,omitempty"§
	Limits   map[string]string §json:"limits,omitempty"§
}

// SecuritySpec configures pod/container hardening.
type SecuritySpec struct {
	RunAsNonRoot             *bool             §json:"runAsNonRoot,omitempty"§
	RunAsUser                *int64            §json:"runAsUser,omitempty"§
	RunAsGroup               *int64            §json:"runAsGroup,omitempty"§
	FSGroup                  *int64            §json:"fsGroup,omitempty"§
	ReadOnlyRootFilesystem   *bool             §json:"readOnlyRootFilesystem,omitempty"§
	AllowPrivilegeEscalation *bool             §json:"allowPrivilegeEscalation,omitempty"§
	Capabilities             *CapabilitiesSpec §json:"capabilities,omitempty"§
	SeccompProfile           string            §json:"seccompProfile,omitempty"§
	WritablePaths            []string          §json:"writablePaths,omitempty"§
}

// CapabilitiesSpec lists Linux capabilities to drop/add.
type CapabilitiesSpec struct {
	Drop []string §json:"drop,omitempty"§
	Add  []string §json:"add,omitempty"§
}

// ProbesSpec configures liveness/readiness/startup probes.
type ProbesSpec struct {
	Path      string     §json:"path,omitempty"§
	Liveness  *ProbeSpec §json:"liveness,omitempty"§
	Readiness *ProbeSpec §json:"readiness,omitempty"§
	Startup   *ProbeSpec §json:"startup,omitempty"§
}

// ProbeSpec overrides one probe.
type ProbeSpec struct {
	Enabled             *bool  §json:"enabled,omitempty"§
	Path                string §json:"path,omitempty"§
	InitialDelaySeconds *int32 §json:"initialDelaySeconds,omitempty"§
	PeriodSeconds       *int32 §json:"periodSeconds,omitempty"§
	TimeoutSeconds      *int32 §json:"timeoutSeconds,omitempty"§
	FailureThreshold    *int32 §json:"failureThreshold,omitempty"§
	SuccessThreshold    *int32 §json:"successThreshold,omitempty"§
}

// StrategySpec configures the Deployment rollout strategy.
type StrategySpec struct {
	Type           string              §json:"type,omitempty"§
	MaxSurge       *intstr.IntOrString §json:"maxSurge,omitempty"§
	MaxUnavailable *intstr.IntOrString §json:"maxUnavailable,omitempty"§
}

// PDBSpec configures the PodDisruptionBudget.
type PDBSpec struct {
	Enabled        *bool               §json:"enabled,omitempty"§
	MinAvailable   *intstr.IntOrString §json:"minAvailable,omitempty"§
	MaxUnavailable *intstr.IntOrString §json:"maxUnavailable,omitempty"§
}
`);

/** builders.go: pure functions turning a service spec into Kubernetes objects. */
export const BUILDERS_GO = goSource(String.raw`package main

import (
	"fmt"
	"path"
	"regexp"
	"sort"
	"strings"

	appsv1 "k8s.io/api/apps/v1"
	corev1 "k8s.io/api/core/v1"
	policyv1 "k8s.io/api/policy/v1"
	"k8s.io/apimachinery/pkg/api/resource"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/util/intstr"
)

const (
	defaultPort       = 8080
	defaultRunAs      = int64(10001)
	defaultReplicas   = int32(2)
	workspaceLabel    = "re-shell.io/workspace"
	managedByLabel    = "app.kubernetes.io/managed-by"
	managedByValue    = "re-shell-operator"
	defaultCPURequest = "100m"
	defaultMemRequest = "128Mi"
	defaultCPULimit   = "500m"
	defaultMemLimit   = "512Mi"
	defaultHistory    = int32(10)
	defaultDeadline   = int32(600)
	nonAlnum          = "[^a-zA-Z0-9]+"
)

var nonAlnumRe = regexp.MustCompile(nonAlnum)

func ptr[T any](v T) *T { return &v }

// deepMerge returns base overlaid with over (maps merge recursively; every
// other value, including arrays, is replaced).
func deepMerge(base, over map[string]interface{}) map[string]interface{} {
	out := map[string]interface{}{}
	for k, v := range base {
		out[k] = v
	}
	for k, v := range over {
		if vm, ok := v.(map[string]interface{}); ok {
			if bm, ok := out[k].(map[string]interface{}); ok {
				out[k] = deepMerge(bm, vm)
				continue
			}
		}
		out[k] = v
	}
	return out
}

// resolveKubernetes merges the workspace-level and service-level kubernetes
// blocks (service wins) and decodes the result.
func resolveKubernetes(spec WorkspaceSpec, svc ServiceSpec) (KubernetesSpec, error) {
	base := map[string]interface{}{}
	if spec.Deployment != nil && spec.Deployment.Replicas != nil {
		base["replicas"] = int64(*spec.Deployment.Replicas)
	}
	merged := deepMerge(deepMerge(base, spec.Kubernetes), svc.Kubernetes)
	var k KubernetesSpec
	if err := runtime.DefaultUnstructuredConverter.FromUnstructured(merged, &k); err != nil {
		return k, fmt.Errorf("decoding kubernetes settings: %w", err)
	}
	return k, nil
}

func serviceLabels(workspace, service string) map[string]string {
	return map[string]string{
		"app":                    service,
		"app.kubernetes.io/name": service,
		managedByLabel:           managedByValue,
		workspaceLabel:           workspace,
	}
}

func volumeName(p string) string {
	n := strings.ToLower(nonAlnumRe.ReplaceAllString(strings.Trim(p, "/"), "-"))
	n = strings.Trim(n, "-")
	if n == "" {
		return "root"
	}
	if len(n) > 63 {
		n = strings.TrimRight(n[:63], "-")
	}
	return n
}

func buildResources(svc ServiceSpec, k KubernetesSpec) (corev1.ResourceRequirements, error) {
	requests := map[string]string{"cpu": defaultCPURequest, "memory": defaultMemRequest}
	limits := map[string]string{"cpu": defaultCPULimit, "memory": defaultMemLimit}
	if r := svc.Resources; r != nil {
		if r.CPU != nil {
			if r.CPU.Request != "" {
				requests["cpu"] = r.CPU.Request
			}
			if r.CPU.Limit != "" {
				limits["cpu"] = r.CPU.Limit
			}
		}
		if r.Memory != nil {
			if r.Memory.Request != "" {
				requests["memory"] = r.Memory.Request
			}
			if r.Memory.Limit != "" {
				limits["memory"] = r.Memory.Limit
			}
		}
	}
	if k.Resources != nil {
		for name, q := range k.Resources.Requests {
			requests[name] = q
		}
		for name, q := range k.Resources.Limits {
			limits[name] = q
		}
	}
	out := corev1.ResourceRequirements{Requests: corev1.ResourceList{}, Limits: corev1.ResourceList{}}
	for name, q := range requests {
		parsed, err := resource.ParseQuantity(q)
		if err != nil {
			return out, fmt.Errorf("invalid request %s=%q: %w", name, q, err)
		}
		out.Requests[corev1.ResourceName(name)] = parsed
	}
	for name, q := range limits {
		parsed, err := resource.ParseQuantity(q)
		if err != nil {
			return out, fmt.Errorf("invalid limit %s=%q: %w", name, q, err)
		}
		out.Limits[corev1.ResourceName(name)] = parsed
	}
	for name, lim := range out.Limits {
		if req, ok := out.Requests[name]; ok && req.Cmp(lim) > 0 {
			return out, fmt.Errorf("%s request (%s) exceeds its limit (%s)", name, req.String(), lim.String())
		}
	}
	return out, nil
}

type probeDefaults struct {
	initialDelay, period, timeout, failure, success int32
}

func buildProbe(d probeDefaults, o *ProbeSpec, healthPath string, hc *HealthCheck) *corev1.Probe {
	if o != nil && o.Enabled != nil && !*o.Enabled {
		return nil
	}
	p := &corev1.Probe{
		InitialDelaySeconds: d.initialDelay,
		PeriodSeconds:       d.period,
		TimeoutSeconds:      d.timeout,
		FailureThreshold:    d.failure,
		SuccessThreshold:    d.success,
	}
	if hc != nil {
		if hc.Interval != nil {
			p.PeriodSeconds = *hc.Interval
		}
		if hc.Timeout != nil {
			p.TimeoutSeconds = *hc.Timeout
		}
		if hc.Retries != nil && *hc.Retries >= 1 {
			p.FailureThreshold = *hc.Retries
		}
	}
	probePath := healthPath
	if o != nil {
		if o.Path != "" {
			probePath = o.Path
		}
		if o.InitialDelaySeconds != nil {
			p.InitialDelaySeconds = *o.InitialDelaySeconds
		}
		if o.PeriodSeconds != nil {
			p.PeriodSeconds = *o.PeriodSeconds
		}
		if o.TimeoutSeconds != nil {
			p.TimeoutSeconds = *o.TimeoutSeconds
		}
		if o.FailureThreshold != nil {
			p.FailureThreshold = *o.FailureThreshold
		}
		if o.SuccessThreshold != nil {
			p.SuccessThreshold = *o.SuccessThreshold
		}
	}
	port := intstr.FromString("http")
	if probePath != "" {
		p.ProbeHandler = corev1.ProbeHandler{HTTPGet: &corev1.HTTPGetAction{Path: probePath, Port: port}}
	} else {
		p.ProbeHandler = corev1.ProbeHandler{TCPSocket: &corev1.TCPSocketAction{Port: port}}
	}
	return p
}

// replicasFor mirrors the CLI generators: explicit replicas, else scaling.min, else 2.
func replicasFor(svc ServiceSpec, k KubernetesSpec) int32 {
	if k.Replicas != nil {
		return *k.Replicas
	}
	if svc.Scaling != nil && svc.Scaling.Min != nil && *svc.Scaling.Min >= 1 {
		return *svc.Scaling.Min
	}
	return defaultReplicas
}

func imageFor(name string, k KubernetesSpec) (string, corev1.PullPolicy) {
	repo, tag, pull := name, "latest", corev1.PullIfNotPresent
	if k.Image != nil {
		if k.Image.Repository != "" {
			repo = k.Image.Repository
		}
		if k.Image.Registry != "" {
			repo = strings.TrimRight(k.Image.Registry, "/") + "/" + repo
		}
		if k.Image.Tag != "" {
			tag = k.Image.Tag
		}
		if k.Image.PullPolicy != "" {
			pull = corev1.PullPolicy(k.Image.PullPolicy)
		}
	}
	return repo + ":" + tag, pull
}

// buildDeployment renders the hardened Deployment for one service.
func buildDeployment(workspace, namespace, name string, spec WorkspaceSpec, svc ServiceSpec, owner metav1.OwnerReference) (*appsv1.Deployment, error) {
	k, err := resolveKubernetes(spec, svc)
	if err != nil {
		return nil, err
	}
	port := svc.Port
	if port == 0 {
		port = defaultPort
	}
	image, pull := imageFor(name, k)
	resources, err := buildResources(svc, k)
	if err != nil {
		return nil, err
	}

	// Security: Pod Security Standards "restricted" by default.
	sc := k.SecurityContext
	if sc == nil {
		sc = &SecuritySpec{}
	}
	runAsNonRoot := true
	if sc.RunAsNonRoot != nil {
		runAsNonRoot = *sc.RunAsNonRoot
	}
	runAsUser := defaultRunAs
	if sc.RunAsUser != nil {
		runAsUser = *sc.RunAsUser
	}
	runAsGroup := defaultRunAs
	if sc.RunAsGroup != nil {
		runAsGroup = *sc.RunAsGroup
	}
	fsGroup := runAsGroup
	if sc.FSGroup != nil {
		fsGroup = *sc.FSGroup
	}
	if runAsNonRoot && runAsUser == 0 {
		return nil, fmt.Errorf("securityContext.runAsNonRoot is true but runAsUser is 0")
	}
	seccomp := corev1.SeccompProfileTypeRuntimeDefault
	if sc.SeccompProfile != "" {
		seccomp = corev1.SeccompProfileType(sc.SeccompProfile)
	}
	rofs := true
	if sc.ReadOnlyRootFilesystem != nil {
		rofs = *sc.ReadOnlyRootFilesystem
	}
	allowEscalation := false
	if sc.AllowPrivilegeEscalation != nil {
		allowEscalation = *sc.AllowPrivilegeEscalation
	}
	drop := []corev1.Capability{"ALL"}
	var add []corev1.Capability
	if sc.Capabilities != nil {
		if sc.Capabilities.Drop != nil {
			drop = nil
			for _, c := range sc.Capabilities.Drop {
				drop = append(drop, corev1.Capability(c))
			}
		}
		for _, c := range sc.Capabilities.Add {
			add = append(add, corev1.Capability(c))
		}
	}
	writable := []string{"/tmp"}
	if sc.WritablePaths != nil {
		writable = sc.WritablePaths
	}
	if !rofs {
		writable = nil
	}

	var mounts []corev1.VolumeMount
	var volumes []corev1.Volume
	for _, p := range writable {
		mounts = append(mounts, corev1.VolumeMount{Name: volumeName(path.Clean(p)), MountPath: p})
		volumes = append(volumes, corev1.Volume{
			Name:         volumeName(path.Clean(p)),
			VolumeSource: corev1.VolumeSource{EmptyDir: &corev1.EmptyDirVolumeSource{}},
		})
	}

	// Probes: httpGet on the declared health path, tcpSocket otherwise.
	healthPath := ""
	if svc.HealthCheck != nil {
		healthPath = svc.HealthCheck.Path
	}
	var live, ready, startup *ProbeSpec
	if k.Probes != nil {
		if k.Probes.Path != "" {
			healthPath = k.Probes.Path
		}
		live, ready, startup = k.Probes.Liveness, k.Probes.Readiness, k.Probes.Startup
	}
	var startupProbe *corev1.Probe
	if startup != nil {
		startupProbe = buildProbe(probeDefaults{0, 5, 3, 30, 1}, startup, healthPath, nil)
	}

	// Rollout strategy + rollback history.
	strategy := appsv1.DeploymentStrategy{
		Type: appsv1.RollingUpdateDeploymentStrategyType,
		RollingUpdate: &appsv1.RollingUpdateDeployment{
			MaxSurge:       ptr(intstr.FromInt32(1)),
			MaxUnavailable: ptr(intstr.FromInt32(0)),
		},
	}
	if k.Strategy != nil {
		if k.Strategy.Type == "Recreate" {
			strategy = appsv1.DeploymentStrategy{Type: appsv1.RecreateDeploymentStrategyType}
		} else {
			if k.Strategy.MaxSurge != nil {
				strategy.RollingUpdate.MaxSurge = k.Strategy.MaxSurge
			}
			if k.Strategy.MaxUnavailable != nil {
				strategy.RollingUpdate.MaxUnavailable = k.Strategy.MaxUnavailable
			}
		}
	}
	history := defaultHistory
	if k.RevisionHistoryLimit != nil {
		history = *k.RevisionHistoryLimit
	}
	deadline := defaultDeadline
	if k.ProgressDeadlineSeconds != nil {
		deadline = *k.ProgressDeadlineSeconds
	}
	minReady := int32(0)
	if k.MinReadySeconds != nil {
		minReady = *k.MinReadySeconds
	}
	automount := false
	if k.AutomountServiceAccountToken != nil {
		automount = *k.AutomountServiceAccountToken
	}

	envNames := make([]string, 0, len(svc.Env))
	for n := range svc.Env {
		envNames = append(envNames, n)
	}
	sort.Strings(envNames)
	var env []corev1.EnvVar
	for _, n := range envNames {
		env = append(env, corev1.EnvVar{Name: n, Value: svc.Env[n]})
	}

	labels := serviceLabels(workspace, name)
	container := corev1.Container{
		Name:            name,
		Image:           image,
		ImagePullPolicy: pull,
		Ports:           []corev1.ContainerPort{{Name: "http", ContainerPort: port}},
		Env:             env,
		Resources:       resources,
		SecurityContext: &corev1.SecurityContext{
			AllowPrivilegeEscalation: ptr(allowEscalation),
			ReadOnlyRootFilesystem:   ptr(rofs),
			RunAsNonRoot:             ptr(runAsNonRoot),
			RunAsUser:                ptr(runAsUser),
			Capabilities:             &corev1.Capabilities{Drop: drop, Add: add},
			SeccompProfile:           &corev1.SeccompProfile{Type: seccomp},
		},
		LivenessProbe:  buildProbe(probeDefaults{10, 10, 3, 3, 0}, live, healthPath, svc.HealthCheck),
		ReadinessProbe: buildProbe(probeDefaults{3, 5, 3, 3, 1}, ready, healthPath, svc.HealthCheck),
		StartupProbe:   startupProbe,
		VolumeMounts:   mounts,
	}

	podSpec := corev1.PodSpec{
		AutomountServiceAccountToken: ptr(automount),
		SecurityContext: &corev1.PodSecurityContext{
			RunAsNonRoot:   ptr(runAsNonRoot),
			RunAsUser:      ptr(runAsUser),
			RunAsGroup:     ptr(runAsGroup),
			FSGroup:        ptr(fsGroup),
			SeccompProfile: &corev1.SeccompProfile{Type: seccomp},
		},
		TerminationGracePeriodSeconds: k.TerminationGracePeriodSeconds,
		Containers:                    []corev1.Container{container},
		Volumes:                       volumes,
	}

	return &appsv1.Deployment{
		TypeMeta: metav1.TypeMeta{APIVersion: "apps/v1", Kind: "Deployment"},
		ObjectMeta: metav1.ObjectMeta{
			Name:            name,
			Namespace:       namespace,
			Labels:          labels,
			OwnerReferences: []metav1.OwnerReference{owner},
		},
		Spec: appsv1.DeploymentSpec{
			Replicas:                ptr(replicasFor(svc, k)),
			RevisionHistoryLimit:    ptr(history),
			ProgressDeadlineSeconds: ptr(deadline),
			MinReadySeconds:         minReady,
			Strategy:                strategy,
			Selector:                &metav1.LabelSelector{MatchLabels: map[string]string{"app": name}},
			Template: corev1.PodTemplateSpec{
				ObjectMeta: metav1.ObjectMeta{Labels: labels},
				Spec:       podSpec,
			},
		},
	}, nil
}

// buildService renders the ClusterIP Service for one service.
func buildService(workspace, namespace, name string, svc ServiceSpec, owner metav1.OwnerReference) *corev1.Service {
	port := svc.Port
	if port == 0 {
		port = defaultPort
	}
	return &corev1.Service{
		TypeMeta: metav1.TypeMeta{APIVersion: "v1", Kind: "Service"},
		ObjectMeta: metav1.ObjectMeta{
			Name:            name,
			Namespace:       namespace,
			Labels:          serviceLabels(workspace, name),
			OwnerReferences: []metav1.OwnerReference{owner},
		},
		Spec: corev1.ServiceSpec{
			Type:     corev1.ServiceTypeClusterIP,
			Selector: map[string]string{"app": name},
			Ports: []corev1.ServicePort{{
				Name:       "http",
				Protocol:   corev1.ProtocolTCP,
				Port:       port,
				TargetPort: intstr.FromInt32(port),
			}},
		},
	}
}

// buildPDB renders the PodDisruptionBudget, or nil when it is disabled.
func buildPDB(workspace, namespace, name string, spec WorkspaceSpec, svc ServiceSpec, owner metav1.OwnerReference) (*policyv1.PodDisruptionBudget, error) {
	k, err := resolveKubernetes(spec, svc)
	if err != nil {
		return nil, err
	}
	if k.PDB != nil && k.PDB.Enabled != nil && !*k.PDB.Enabled {
		return nil, nil
	}
	pdb := &policyv1.PodDisruptionBudget{
		TypeMeta: metav1.TypeMeta{APIVersion: "policy/v1", Kind: "PodDisruptionBudget"},
		ObjectMeta: metav1.ObjectMeta{
			Name:            name,
			Namespace:       namespace,
			Labels:          serviceLabels(workspace, name),
			OwnerReferences: []metav1.OwnerReference{owner},
		},
		Spec: policyv1.PodDisruptionBudgetSpec{
			Selector: &metav1.LabelSelector{MatchLabels: map[string]string{"app": name}},
		},
	}
	switch {
	case k.PDB != nil && k.PDB.MinAvailable != nil && k.PDB.MaxUnavailable != nil:
		return nil, fmt.Errorf("pdb.minAvailable and pdb.maxUnavailable are mutually exclusive")
	case k.PDB != nil && k.PDB.MinAvailable != nil:
		pdb.Spec.MinAvailable = k.PDB.MinAvailable
	case k.PDB != nil && k.PDB.MaxUnavailable != nil:
		pdb.Spec.MaxUnavailable = k.PDB.MaxUnavailable
	case replicasFor(svc, k) >= 2:
		pdb.Spec.MinAvailable = ptr(intstr.FromInt32(1))
	default:
		// A single replica must stay evictable for node drains.
		pdb.Spec.MaxUnavailable = ptr(intstr.FromInt32(1))
	}
	return pdb, nil
}
`);

/** reconciler.go: the controller. */
export const RECONCILER_GO = goSource(String.raw`package main

import (
	"context"
	"fmt"
	"sort"
	"time"

	appsv1 "k8s.io/api/apps/v1"
	corev1 "k8s.io/api/core/v1"
	policyv1 "k8s.io/api/policy/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/runtime/schema"
	ctrl "sigs.k8s.io/controller-runtime"
	"sigs.k8s.io/controller-runtime/pkg/client"
)

// fieldManager is the server-side-apply field owner of everything we create.
const fieldManager = "re-shell-operator"

// workspaceGVK is the custom resource this controller reconciles.
var workspaceGVK = schema.GroupVersionKind{Group: Group, Version: Version, Kind: Kind}

func newWorkspace() *unstructured.Unstructured {
	ws := &unstructured.Unstructured{}
	ws.SetGroupVersionKind(workspaceGVK)
	return ws
}

// WorkspaceReconciler reconciles a ReShellWorkspace into Deployments, Services
// and PodDisruptionBudgets (one set per entry under spec.services).
//
// The custom resource is handled as unstructured so the scaffold needs no
// generated deepcopy code; the spec is decoded into WorkspaceSpec.
type WorkspaceReconciler struct {
	client.Client
	Scheme *runtime.Scheme
}

// SetupWithManager registers the controller.
func (r *WorkspaceReconciler) SetupWithManager(mgr ctrl.Manager) error {
	return ctrl.NewControllerManagedBy(mgr).
		Named("reshellworkspace").
		For(newWorkspace()).
		Owns(&appsv1.Deployment{}).
		Owns(&corev1.Service{}).
		Owns(&policyv1.PodDisruptionBudget{}).
		Complete(r)
}

type serviceStatus struct {
	Name            string
	DesiredReplicas int32
	ReadyReplicas   int32
	Available       bool
}

// Reconcile drives the cluster toward the ReShellWorkspace spec.
func (r *WorkspaceReconciler) Reconcile(ctx context.Context, req ctrl.Request) (ctrl.Result, error) {
	log := ctrl.LoggerFrom(ctx)

	ws := newWorkspace()
	if err := r.Get(ctx, req.NamespacedName, ws); err != nil {
		return ctrl.Result{}, client.IgnoreNotFound(err)
	}
	if !ws.GetDeletionTimestamp().IsZero() {
		// Owned objects are garbage-collected through their owner references.
		return ctrl.Result{}, nil
	}

	specMap, found, err := unstructured.NestedMap(ws.Object, "spec")
	if err != nil || !found {
		return ctrl.Result{}, r.setStatus(ctx, ws, "Degraded", nil, "InvalidSpec", "spec is missing or not an object")
	}
	var spec WorkspaceSpec
	if err := runtime.DefaultUnstructuredConverter.FromUnstructured(specMap, &spec); err != nil {
		return ctrl.Result{}, r.setStatus(ctx, ws, "Degraded", nil, "InvalidSpec", err.Error())
	}

	owner := metav1.OwnerReference{
		APIVersion:         ws.GetAPIVersion(),
		Kind:               ws.GetKind(),
		Name:               ws.GetName(),
		UID:                ws.GetUID(),
		Controller:         ptr(true),
		BlockOwnerDeletion: ptr(true),
	}
	namespace := ws.GetNamespace()

	names := make([]string, 0, len(spec.Services))
	for name := range spec.Services {
		names = append(names, name)
	}
	sort.Strings(names)

	desired := map[string]bool{}
	var statuses []serviceStatus
	for _, name := range names {
		svc := spec.Services[name]
		desired[name] = true

		dep, err := buildDeployment(ws.GetName(), namespace, name, spec, svc, owner)
		if err != nil {
			return ctrl.Result{}, r.setStatus(ctx, ws, "Degraded", statuses, "InvalidService", fmt.Sprintf("service %q: %v", name, err))
		}
		if err := r.apply(ctx, dep); err != nil {
			return ctrl.Result{}, fmt.Errorf("applying Deployment %s: %w", name, err)
		}
		if err := r.apply(ctx, buildService(ws.GetName(), namespace, name, svc, owner)); err != nil {
			return ctrl.Result{}, fmt.Errorf("applying Service %s: %w", name, err)
		}
		pdb, err := buildPDB(ws.GetName(), namespace, name, spec, svc, owner)
		if err != nil {
			return ctrl.Result{}, r.setStatus(ctx, ws, "Degraded", statuses, "InvalidService", fmt.Sprintf("service %q: %v", name, err))
		}
		if pdb != nil {
			if err := r.apply(ctx, pdb); err != nil {
				return ctrl.Result{}, fmt.Errorf("applying PodDisruptionBudget %s: %w", name, err)
			}
		} else if err := r.deleteIfOwned(ctx, &policyv1.PodDisruptionBudget{ObjectMeta: metav1.ObjectMeta{Name: name, Namespace: namespace}}, ws); err != nil {
			return ctrl.Result{}, err
		}

		// r.apply refreshed dep with the server's view, including status.
		replicas := int32(1)
		if dep.Spec.Replicas != nil {
			replicas = *dep.Spec.Replicas
		}
		statuses = append(statuses, serviceStatus{
			Name:            name,
			DesiredReplicas: replicas,
			ReadyReplicas:   dep.Status.ReadyReplicas,
			Available:       dep.Status.ObservedGeneration >= dep.Generation && dep.Status.UpdatedReplicas == replicas && dep.Status.AvailableReplicas >= replicas,
		})
	}

	if err := r.prune(ctx, ws, desired); err != nil {
		return ctrl.Result{}, err
	}

	phase, reason, message := "Ready", "AllServicesAvailable", "all service Deployments are available"
	for _, s := range statuses {
		if !s.Available {
			phase, reason, message = "Progressing", "RolloutInProgress", fmt.Sprintf("service %q has %d/%d ready replicas", s.Name, s.ReadyReplicas, s.DesiredReplicas)
			break
		}
	}
	log.Info("reconciled", "workspace", ws.GetName(), "services", len(names), "phase", phase)
	if err := r.setStatus(ctx, ws, phase, statuses, reason, message); err != nil {
		return ctrl.Result{}, err
	}
	if phase != "Ready" {
		// Deployment status changes also trigger reconciles; this is a safety net.
		return ctrl.Result{RequeueAfter: 30 * time.Second}, nil
	}
	return ctrl.Result{}, nil
}

// apply server-side-applies an object we own.
func (r *WorkspaceReconciler) apply(ctx context.Context, obj client.Object) error {
	return r.Patch(ctx, obj, client.Apply, client.FieldOwner(fieldManager), client.ForceOwnership)
}

// isOwnedBy reports whether obj is controlled by ws.
func isOwnedBy(obj metav1.Object, ws *unstructured.Unstructured) bool {
	ref := metav1.GetControllerOf(obj)
	return ref != nil && ref.UID == ws.GetUID()
}

// deleteIfOwned deletes obj when it exists and is controlled by ws.
func (r *WorkspaceReconciler) deleteIfOwned(ctx context.Context, obj client.Object, ws *unstructured.Unstructured) error {
	if err := r.Get(ctx, client.ObjectKeyFromObject(obj), obj); err != nil {
		return client.IgnoreNotFound(err)
	}
	if !isOwnedBy(obj, ws) {
		return nil
	}
	return client.IgnoreNotFound(r.Delete(ctx, obj))
}

// prune deletes owned Deployments/Services/PDBs whose service left the spec.
func (r *WorkspaceReconciler) prune(ctx context.Context, ws *unstructured.Unstructured, desired map[string]bool) error {
	opts := []client.ListOption{
		client.InNamespace(ws.GetNamespace()),
		client.MatchingLabels{workspaceLabel: ws.GetName()},
	}

	deployments := &appsv1.DeploymentList{}
	if err := r.List(ctx, deployments, opts...); err != nil {
		return err
	}
	for i := range deployments.Items {
		d := &deployments.Items[i]
		if !desired[d.Name] && isOwnedBy(d, ws) {
			if err := client.IgnoreNotFound(r.Delete(ctx, d)); err != nil {
				return err
			}
		}
	}

	services := &corev1.ServiceList{}
	if err := r.List(ctx, services, opts...); err != nil {
		return err
	}
	for i := range services.Items {
		s := &services.Items[i]
		if !desired[s.Name] && isOwnedBy(s, ws) {
			if err := client.IgnoreNotFound(r.Delete(ctx, s)); err != nil {
				return err
			}
		}
	}

	budgets := &policyv1.PodDisruptionBudgetList{}
	if err := r.List(ctx, budgets, opts...); err != nil {
		return err
	}
	for i := range budgets.Items {
		b := &budgets.Items[i]
		if !desired[b.Name] && isOwnedBy(b, ws) {
			if err := client.IgnoreNotFound(r.Delete(ctx, b)); err != nil {
				return err
			}
		}
	}
	return nil
}

// setStatus writes status.phase / services / conditions through the status
// subresource.
func (r *WorkspaceReconciler) setStatus(ctx context.Context, ws *unstructured.Unstructured, phase string, services []serviceStatus, reason, message string) error {
	svcList := make([]interface{}, 0, len(services))
	for _, s := range services {
		svcList = append(svcList, map[string]interface{}{
			"name":            s.Name,
			"desiredReplicas": int64(s.DesiredReplicas),
			"readyReplicas":   int64(s.ReadyReplicas),
			"available":       s.Available,
		})
	}

	status := "False"
	if phase == "Ready" {
		status = "True"
	}
	now := metav1.Now().UTC().Format(time.RFC3339)
	// Preserve lastTransitionTime when the Ready condition did not change.
	if existing, found, _ := unstructured.NestedSlice(ws.Object, "status", "conditions"); found {
		for _, c := range existing {
			cm, ok := c.(map[string]interface{})
			if ok && cm["type"] == "Ready" && cm["status"] == status {
				if t, ok := cm["lastTransitionTime"].(string); ok && t != "" {
					now = t
				}
			}
		}
	}
	conditions := []interface{}{map[string]interface{}{
		"type":               "Ready",
		"status":             status,
		"reason":             reason,
		"message":            message,
		"lastTransitionTime": now,
		"observedGeneration": ws.GetGeneration(),
	}}

	if err := unstructured.SetNestedField(ws.Object, ws.GetGeneration(), "status", "observedGeneration"); err != nil {
		return err
	}
	if err := unstructured.SetNestedField(ws.Object, phase, "status", "phase"); err != nil {
		return err
	}
	if err := unstructured.SetNestedSlice(ws.Object, svcList, "status", "services"); err != nil {
		return err
	}
	if err := unstructured.SetNestedSlice(ws.Object, conditions, "status", "conditions"); err != nil {
		return err
	}
	return r.Status().Update(ctx, ws)
}
`);

/** main.go: manager bootstrap. */
export const MAIN_GO = goSource(String.raw`package main

import (
	"flag"
	"os"

	"k8s.io/apimachinery/pkg/runtime"
	utilruntime "k8s.io/apimachinery/pkg/util/runtime"
	clientgoscheme "k8s.io/client-go/kubernetes/scheme"
	ctrl "sigs.k8s.io/controller-runtime"
	"sigs.k8s.io/controller-runtime/pkg/healthz"
	"sigs.k8s.io/controller-runtime/pkg/log/zap"
	metricsserver "sigs.k8s.io/controller-runtime/pkg/metrics/server"
)

var (
	scheme   = runtime.NewScheme()
	setupLog = ctrl.Log.WithName("setup")
)

func init() {
	utilruntime.Must(clientgoscheme.AddToScheme(scheme))
}

func main() {
	var metricsAddr, probeAddr string
	var leaderElect bool
	flag.StringVar(&metricsAddr, "metrics-bind-address", ":8080", "address the metrics endpoint binds to (0 disables it)")
	flag.StringVar(&probeAddr, "health-probe-bind-address", ":8081", "address the health probe endpoint binds to")
	flag.BoolVar(&leaderElect, "leader-elect", false, "enable leader election (required when running more than one replica)")
	opts := zap.Options{Development: true}
	opts.BindFlags(flag.CommandLine)
	flag.Parse()
	ctrl.SetLogger(zap.New(zap.UseFlagOptions(&opts)))

	mgr, err := ctrl.NewManager(ctrl.GetConfigOrDie(), ctrl.Options{
		Scheme:                 scheme,
		Metrics:                metricsserver.Options{BindAddress: metricsAddr},
		HealthProbeBindAddress: probeAddr,
		LeaderElection:         leaderElect,
		LeaderElectionID:       Plural + "." + Group,
	})
	if err != nil {
		setupLog.Error(err, "unable to start manager")
		os.Exit(1)
	}

	if err := (&WorkspaceReconciler{Client: mgr.GetClient(), Scheme: mgr.GetScheme()}).SetupWithManager(mgr); err != nil {
		setupLog.Error(err, "unable to create controller", "controller", Kind)
		os.Exit(1)
	}
	if err := mgr.AddHealthzCheck("healthz", healthz.Ping); err != nil {
		setupLog.Error(err, "unable to set up health check")
		os.Exit(1)
	}
	if err := mgr.AddReadyzCheck("readyz", healthz.Ping); err != nil {
		setupLog.Error(err, "unable to set up ready check")
		os.Exit(1)
	}

	setupLog.Info("starting manager")
	if err := mgr.Start(ctrl.SetupSignalHandler()); err != nil {
		setupLog.Error(err, "problem running manager")
		os.Exit(1)
	}
}
`);

/** Dockerfile for the operator image. */
export const DOCKERFILE = `# Build the operator, then ship it on a distroless non-root base.
FROM golang:1.24 AS build
WORKDIR /src
COPY go.mod go.sum* ./
RUN go mod download
COPY *.go ./
RUN CGO_ENABLED=0 GOOS=linux go build -trimpath -ldflags="-s -w" -o /out/manager .

FROM gcr.io/distroless/static:nonroot
COPY --from=build /out/manager /manager
USER 65532:65532
ENTRYPOINT ["/manager"]
`;

/** Makefile with the everyday targets. */
export function makefile(crdFile: string): string {
  return `IMG ?= reshell-operator:latest

.PHONY: build run test install uninstall deploy undeploy docker-build tidy

tidy:
	go mod tidy

build: tidy
	go build -o bin/manager .

# Run the controller against the cluster in $KUBECONFIG (CRD must be installed).
run: tidy
	go run .

test: tidy
	go vet ./...

# Install / remove the ReShellWorkspace CRD.
install:
	kubectl apply --server-side -f ${crdFile}

uninstall:
	kubectl delete -f ${crdFile}

docker-build:
	docker build -t $(IMG) .

# Deploy the operator (namespace, RBAC, Deployment) into the cluster.
deploy: install
	kubectl apply -f config/manager/namespace.yaml
	kubectl apply -f config/rbac/
	kubectl apply -f config/manager/manager.yaml

undeploy:
	kubectl delete -f config/manager/manager.yaml --ignore-not-found
	kubectl delete -f config/rbac/ --ignore-not-found
	kubectl delete -f config/manager/namespace.yaml --ignore-not-found
`;
}

/** .gitignore for the scaffold. */
export const GITIGNORE = `bin/
*.test
`;
