import { Command } from 'commander';
import { createAsyncCommand, withTimeout } from '../../utils/error-handler';
import chalk from 'chalk';

/**
 * Registers the `collab knowledge-sharing-automation` subcommand.
 * Extracted verbatim from the former monolithic collab.group.ts.
 */
export function registerKnowledgeSharingAutomation(collab: Command): void {
  collab
  .command('knowledge-sharing-automation')
  .description('Generate knowledge sharing and documentation automation with AI assistance')
  .argument('<name>', 'Name of the knowledge sharing automation setup')
  .option('--ai-provider <provider>', 'AI provider (openai, anthropic, cohere, local)', 'openai')
  .option('--enable-auto-generation', 'Enable automated documentation generation')
  .option('--enable-versioning', 'Enable documentation versioning')
  .option('--enable-sync', 'Enable documentation sync')
  .option('--enable-aws', 'Enable AWS integration')
  .option('--enable-azure', 'Enable Azure integration')
  .option('--enable-gcp', 'Enable GCP integration')
  .option('--output <dir>', 'Output directory', './knowledge-sharing-automation')
  .option('--language <lang>', 'Language for manager code (typescript|python)', 'typescript')
  .action(createAsyncCommand(async (name, options) => {
    const { writeFiles, displayConfig } = await import('../../utils/knowledge-sharing-automation.js');

    const providers: ('aws' | 'azure' | 'gcp')[] = [];
    if (options.enableAws) providers.push('aws');
    if (options.enableAzure) providers.push('azure');
    if (options.enableGcp) providers.push('gcp');

    const config = {
      projectName: name,
      providers,
      templates: [
        {
          id: 'template1',
          name: 'API Documentation Template',
          type: 'api-doc' as const,
          content: '# {{serviceName}} API Documentation\n\n## Overview\n\n{{description}}\n\n## Endpoints\n\n{{endpoints}}',
          variables: ['serviceName', 'description', 'endpoints'],
          autoGenerated: true,
        },
        {
          id: 'template2',
          name: 'README Template',
          type: 'readme' as const,
          content: '# {{projectName}}\n\n{{description}}\n\n## Installation\n\n{{installation}}\n\n## Usage\n\n{{usage}}',
          variables: ['projectName', 'description', 'installation', 'usage'],
          autoGenerated: true,
        },
      ],
      rules: [
        {
          id: 'rule1',
          name: 'Auto-generate API docs on code change',
          trigger: 'code-change' as const,
          source: 'src/api/**/*.ts',
          template: 'template1',
          destination: 'docs/api/',
          aiEnabled: true,
          aiTasks: ['generation' as const, 'enhancement' as const],
        },
        {
          id: 'rule2',
          name: 'Update README on commit',
          trigger: 'commit' as const,
          source: 'README.md',
          template: 'template2',
          destination: './',
          aiEnabled: true,
          aiTasks: ['summarization' as const, 'formatting' as const],
        },
      ],
      knowledgeBases: [
        {
          id: 'kb1',
          name: 'Project Documentation',
          description: 'Centralized knowledge base for all project documentation',
          documents: ['docs/api/*.md', 'docs/guides/*.md', 'README.md'],
          categories: ['API', 'Guides', 'Getting Started'],
          tags: ['documentation', 'api', 'tutorials'],
          searchEnabled: true,
          indexingEnabled: true,
        },
      ],
      ai: {
        enabled: true,
        provider: options.aiProvider as ('openai' | 'anthropic' | 'cohere' | 'local'),
        model: 'gpt-4',
        maxTokens: 2000,
        temperature: 0.7,
      },
      enableAutoGeneration: options.enableAutoGeneration || false,
      enableVersioning: options.enableVersioning || false,
      enableSync: options.enableSync || false,
    };

    displayConfig(config);

    console.log(chalk.gray('Generating knowledge sharing automation configuration...'));

    await withTimeout(async () => {
      await writeFiles(config, options.output, options.language);
      console.log(chalk.green(`\n✅ Generated: knowledge-sharing-automation.tf`));
      console.log(chalk.green(`✅ Generated: knowledge-sharing-automation-manager.${options.language === 'typescript' ? 'ts' : 'py'}`));
      console.log(chalk.green(`✅ Generated: KNOWLEDGE_SHARING_AUTOMATION.md`));
      console.log(chalk.green(`✅ Generated: package.json (${options.language === 'typescript' ? 'TypeScript' : 'Python'}) or requirements.txt (Python)`));
      console.log(chalk.green(`✅ Generated: knowledge-sharing-automation-config.json\n`));

      console.log(chalk.green('✓ Knowledge sharing automation configuration generated successfully!'));
    }, 30000);
  }));

// Skills assessment commands
}
